### ISSUE TITLE
Screen mirroring/rotation causes BSOD

### ISSUE THREAD

**Issue by eugenesan** [ClockSelect/myevic#10]
Triggering Screen mirroring/rotation causes BSOD (BlackScreenOfDeath).
To reproduce (_steps 4-7 are optional_):
1. Turn off the device (FiveClick)
2. Press and hold + and - buttons until screen rotates
3. Wait until screen goes off
_4. Turn the device on (FiveClick)
5. Do anything
6. Turn off the device (FiveClick)
7. Press and hold + and - buttons until screen rotates_
8. Observe BSOD

To restore normal operation, re-insert the battery.

**Comment by ClockSelect** [comment]
It's not due to screen flipping.
Just switch off the device and click on + or - only is enough.
Unfortunatly I don't get to the BSOD, it only freezes the device.
Investigating.

**Comment by ClockSelect** [comment]
Fixed.
Was due to incorrect clearing of GPIO D interrupt flags.
