### ISSUE TITLE
Wismec RX 1/3

### ISSUE THREAD

**Issue by falconettt** [ClockSelect/myevic#100]
A situation may arise when you have only one battery. Is it possible to make box work in this situation? Now only 2 or 3. Unless of course you're gonna think this idea is interesting...

**Comment by bluenazgul** [comment]
Only one Battery is not possible without Hardware modification

**Comment by ClockSelect** [comment]
Does the box light up when shortcutting the second battery placeholder, and closing the backcap?
After all, the two batteries configuration is only a shortcut of the third cell connectors.

**Comment by Filo301** [comment]
@ClockSelect Yes, it does light up. Maybe you can add option for rx200s (2/3cells)?

**Comment by ClockSelect** [comment]
@Filo301 I just have some code to _remove_ do do that :)
What would do you use as a fake shortcutting battery cell?

**Comment by Filo301** [comment]
@ClockSelect  I dont have rx200s, but it's interesting feature. For test i used short cable.
With one battery rx say "no atomizer".

**Comment by bluenazgul** [comment]
I think there is no need for two Batteries on the RX200S or a single Batterie on RX200S / RX2/3 as it need an "Hardware Modification" on both devices

**Comment by ClockSelect** [comment]
@bluenazgul : no, it just needs a dummy battery that shortcuts the connector, just like the backcap of the RX2/3 does when it's used in dual-cell setting.

Something like: ![](https://www.dropbox.com/s/x3w9nmo06ua9v8r/18650dummybattery.jpg?dl=1)

The problem is not there.
The problem of thoses boxes in single-cell mode is that there's no boost dc-dc converter, so the voltage would be very limited and the box would only vape in low powers like, maybe, 15~20W.

**Comment by ClockSelect** [comment]
I uniformized the battery management code between the two boxes so now you can do what you want.
To reduce the number of cells, you have to short the 3rd battery connector to go dual-cell, and the 3rd and 2nd to go single-cell.

On RX2/3, the 3rd is the rearmost (the one in the backcap), the 2nd is the right one when looking into the battery compartiment.

On RX200S, the 3rd is the right one in the compartiment, and the 2nd is the rearmost.

**Comment by Filo301** [comment]
One cell configuration does not work :( rx didn't read atomizer resistance.

**Comment by Janishewskiiy** [comment]
It would be nice to provide for and possibility of parallel connection of batteries. This may require increasing the current limit.

**Comment by Filo301** [comment]
@Janishewskiiy but probably impossible in rx200s/23/etc.

**Comment by ClockSelect** [comment]
Serial or parallel changes nothing through a dc-dc converter.
P=UI ; halve U and double I, what do you get?

**Comment by Filo301** [comment]
No balancer needed and in rx max 3v on output.

**Comment by falconettt** [comment]
WOW!
It remains to find an elegant way to short the contacts and it's done. 
Do I understand correctly that to make box work at all without a battery in the passthrough mode is impossible?

**Comment by ClockSelect** [comment]
@falconettt : yes; circuit must be closed if you want the current to run through.

**Comment by ClockSelect** [comment]
@Filo301: did you retry with latest commit?

**Comment by Filo301** [comment]
I tried again but with no luck, still "no atomizer"

**Comment by falconettt** [comment]
Yes, RX2/3 in dual-cell mode, right battery compartment shortened with bolt (unknown resistance).
Mod shows coil 0.00 and "no atomizer"

**Comment by falconettt** [comment]
The miracle did not happen...
