### ISSUE TITLE
RX200S wattage

### ISSUE THREAD

**Issue by XqqsMe** [ClockSelect/myevic#101]
Wattage on RX200S with latest factory firmware is 250 watts. My evict only goes to 91. Anything I'm doing wrong?

**Comment by dywersant** [comment]
Whats your coil resistance?

**Comment by ClockSelect** [comment]
This is perfectly normal if your coil is below 0.036 or over 0.89.

**Comment by afol2** [comment]
Maybe is hitting more than 50 amps ?

**Comment by XqqsMe** [comment]
It was my resistance. Sorry for the trouble.
