### ISSUE TITLE
Presa TC 100

### ISSUE THREAD

**Issue by OlafKroll** [ClockSelect/myevic#102]
If I press shows the box 50 watts, however, only felt 20 watts arrive.
This happens every third or fourth time.
With the original firmware does not happen.

**Comment by ClockSelect** [comment]
I hardly see how it can be; do you have another single-cell box where you can install the firmware and the same ato setup, to see if the issue is specific to the TC100 or not? I'd really need some more informations if I hope beeing able to investigate.

**Comment by dabugen** [comment]
Hi, I´ve finally got my Presa TC 100 today and already flashed it, seems to work fine for the last 10 minutes at least, but I will report back, also if I get the same issue like the topic creator.... (so far not)

**Comment by dabugen** [comment]
First 10 hours done, everything just as perfect as I could imagine with your firmware. Am in TCR M1 mode with custom settings (350) for Titan 0.34mm, works like a charm, absolutely happy!

**Comment by ClockSelect** [comment]
@OlafKroll : What's your setup? Does it happen with every atomizer/coil?

**Comment by OlafKroll** [comment]
I tested only on one Setup! (OBS Engine 0,9Ohm dual)
Tomorrow i will test a new config!

**Comment by dabugen** [comment]
First 24 hours+ are done now with my new Presa 100 TC and it has been going all fine. Are you also using TCR M1 mode or just Power mode?

**Comment by OlafKroll** [comment]
only Power

**Comment by ClockSelect** [comment]
@OlafKroll : Does enabling/disabling or tweaking the preheat feature changes something?

**Comment by OlafKroll** [comment]
I flashed yesterday the latest bios.
Since then, the device fires properly.
For me that is thus positively done.
Thank you for your attention.

**Comment by ClockSelect** [comment]
What worries me is that I've done _nothing_.
But I had a report of this very same issue on a forum, user saying it happens only when he uses preheat feature.  So... let's keep looking.

**Comment by OlafKroll** [comment]
I also had the Preheat function turned on as this happened

**Comment by ClockSelect** [comment]
I suspect something in the buck<>boost transition of the dc-dc converter.
If you show the battery voltage next to the battery, and the at volts on the third line, you should be able to see when the atomizer voltage steps above the battery voltage (happens at powers ~35W+). If it's what I suspect, it should happen at this moment.
The moment of tranqition depends on several factors (inhalation strength, battery charge, etc) so the event may happen randomly when vaping between 30 and 40W. The preheat may just help crossing the line.
Could you check that?
Unfortunately I've no Presa by hand.

**Comment by ClockSelect** [comment]
You may give a try to the last commit.
Couldn't test it on Presa unfortunately, so I can only hope it'll solve the problem.

**Comment by OlafKroll** [comment]
Iam always above 40W.
My settings.... 65W (Preheat) and 50W Vape.
And the Akku was full.

**Comment by ClockSelect** [comment]
So? Did you see an improvement?

**Comment by Daveee10** [comment]
On presa 75w the issue is solved. No problem anymore. Waiting the answer for presa 100

**Comment by OlafKroll** [comment]
No problem anymore...... to
