### ISSUE TITLE
add more game?

### ISSUE THREAD

**Issue by damian140920** [ClockSelect/myevic#103]
maybe you add more simple games like snake ?

**Comment by Filo301** [comment]
better arkanoid cause we use only two buttons.

**Comment by ReaLx3m** [comment]
I vote Battlefield 4 ... and while youre at it add multiplayer too... I have few more suggestions, but first lets have this done, and before you know it we will all be selling our PS4's

**Comment by damian140920** [comment]
I think that the connection of the USB gamepad is possible ..... so gta 5 on e cigarette is coming!

**Comment by ClockSelect** [comment]
Well, I'm afraid it's not planned in a near future; I have some project in-between more related to vaping quality and I think I'll focus on it.

**Comment by anderlobo** [comment]
You could add more screen saver

**Comment by dabugen** [comment]
Please focus on vaping quality, if I want to play games, I´ll use my PC or smartphone! Come on guys, this is a e-cigarette!

**Comment by fonix232** [comment]
I think even the Vapy Bird is unnecessary here. This is a freaking e-cigarette, not a handheld gaming platform. Do you want to vape, or do you want to game? If latter, go buy a used PS Vita or Nintendo 3DS...

**Comment by ClockSelect** [comment]
I'd be prone to agree.
Flappy Bird, albeit a fun technical performance, was not a so good idea in the first place.
I keep it because it uses few ressources, but it may not last forever. APROM size is very limited.
Anyway, I do not plan writing games ATM. But remember you can fork the project if you wish :)

**Comment by SEEKNDESTROY** [comment]
I wouldn't be sad if you remove Flappy Bird. I use my mod to vape and not to play games.
