### ISSUE TITLE
Exclamation Mark?

### ISSUE THREAD

**Issue by MoDuLah** [ClockSelect/myevic#112]
**Box Model: Cuboid**

**Coil setup: Dual Twisted Clapton Coils @0.29Ω**

I have starting to use  this myevic firmware the last few hours and i see an exlamation mark (!) next to the battery. But no matter what i do/change it doesn't go away.
Tried to look about it on the manual with no luck. 
Thank you in advance.

![2016 10 30 15 18 24](https://cloud.githubusercontent.com/assets/7404959/19836794/23de2c3c-9eb4-11e6-9898-494b3a60a463.png)

**Comment by ClockSelect** [comment]
You're using th NFE Edition of the firmware.
This is a russian branch different from mine, and I do not work on it.
But AFAIK, the exclamation mark is her to inform you that the Light Sleep mode is On in the settings.
(Expert menu>LSL)

**Comment by MoDuLah** [comment]
Oh ok. Thank you.
Sorry for the inconvenience.
