### ISSUE TITLE
Disable the clock or maybe add an option to disable it?

### ISSUE THREAD

**Issue by SEEKNDESTROY** [ClockSelect/myevic#114]
**Box Model:RX200S**

**Coil setup: 24 gauge dual SS macro coils**

Is there a way to disable the clock or maybe add an option to disable it? I really have no use for it and don't need something draining my batteries no matter few mAh's the clock using.

Thanks in advance.

**Comment by ClockSelect** [comment]
Set X32 to OFF (should already be the case) and LSL to OFF in the Expert menu to suppress any extra battery drain (it's a very low drain anyway; would takes monthes to empty the batteries).
Disable the clock display on double-click in the Interface>Clicks menu.
Shouldn't bother you anymore.

**Comment by SEEKNDESTROY** [comment]
Thanks ClockSelect.
