### ISSUE TITLE
Evic VTwo mini owner wanted for the TC monitoring report to compare

### ISSUE THREAD

**Issue by falconettt** [ClockSelect/myevic#117]
Old Evic mini with FW myevic is great but I need second one as spare.
What one battery mod is most accurate  and best suits your project? 
(My new RX2/3 found a new owner because it heats up when charging and vaping)

**Comment by SEEKNDESTROY** [comment]
**RX200S is my personal favorite but then I don't charge and vape. I charge 3 sets of batteries in external chargers. Plus, Wismec does NOT recommend charging via USB port anyway. I think you should've kept the RX2/3 and invested in another set of batteries and an external charger like the [Luc 4](https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=luc+4+charger&rh=i%3Aaps%2Ck%3Aluc+4+charger) IMHO.**

**Comment by falconettt** [comment]
@SEEKNDESTROY  thanks for the advice, but I vape at 20w, and prefer to charge via USB.
One battery box and a couple of spare batteries IMO is all I need.
But what one battery box is most accurate and best suits myevic firmware?
I'd be quite happy with eVic VTwo, but may be better decision?

**Comment by ClockSelect** [comment]
The best for the project would be one of each of the 14.
Really, buy what pleases you more.
VTwo is a very nice box; you may also consider the Dual, for almost the same price. I like it because it's flawless in temp control. Very accurate and consistent readings giving a very stable vape. I guess VTwo must be almost the same, but did not really test. It depends on when in the design process they improved their components.
I don't know about all the other boxes.

**Comment by lojpek** [comment]
I love my presa 75W TC for small size and button that I can press by hand (don't need to search my fingers for button). Only one con that you must spray it with color, because wismec have very poor paint.

**Comment by falconettt** [comment]
Yes, presa 75W TC looks good on the picture, but black color makes me sad and poor paint is not to deal with.

eVic VTC Dual 
is more accurate in temp control (I'm happy without TC), but has a crack on the upper plane, which may cause the ingress of liquid inside.

So the eVic VTC Mini seems to be ideal.(25$)

But what about eVic VTwo Mini? Does it have any real advantages exept clock accuracy?

**Comment by ClockSelect** [comment]
On the paper, a VTwo Mini is a VTC Mini with a clock, period.
After that, since it's more recent, they may have tuned the electronics in some ways. For example, the Dual is better than the VTC for resistance reading. There must have been some tuning in between. I can't tell about the VTwo since I don't have one by hand to test. I should see a TC monitoring report with PID algorithm to compare.

**Comment by ClockSelect** [comment]
Just to judge the quality of electronics:

eVic VTC Mini, SS316L 0.75Ω @ 180°C, 75W:
![](https://www.dropbox.com/s/sntkxnfrnje5l59/monvtcpid.png?dl=1)

eVic VTC Dual, same setup & config:
![](https://www.dropbox.com/s/t6h6qpjr06c9kf3/mondualpid.png?dl=1)

Obviously, they changed something.
I'd like to see the same for the VTwo.

**Comment by falconettt** [comment]
So, "help wanted"
could anybody be so kind to give us
evic VTwo TC monitoring report with PID algorithm to compare?

**Comment by enricorov** [comment]
I can help, but I'll need some explaination on what to test, and how to provide graphs.

**Comment by falconettt** [comment]
@enricorov : you need to know how to manage with NFirmwareEditor but it's a bit difficult to explain in one sentence...

**Comment by enricorov** [comment]
![immagine](https://cloud.githubusercontent.com/assets/23199149/19941756/b6a2c698-a131-11e6-8acb-59f3d9af9d13.png)

Don't know how to export graphs on NFE, so here's a screenshot.

PID algorithm, VTwo mini, TI 0.15Ω @ 220°C, 60W.

**Comment by falconettt** [comment]
@enricorov , great thanks, may be thats enough for @ClockSelect to to make the right decision...

**Comment by ClockSelect** [comment]
@enricorov: wow... what are your PID parameters?
should be 600/850/0 by default.
Shouldn't make this temperature spike.

**Comment by enricorov** [comment]
My values are the default ones, that is 600/850/0.

**Comment by ClockSelect** [comment]
So maybe it's just a false reading of temp. It happens.

Anyway, VTwo seems to have the same accuracy as the Dual.
Better than the VTC anyway.

**Comment by ClockSelect** [comment]
@falconettt : it's your decision, not mine. I'm just collecting data to help^^

**Comment by falconettt** [comment]
OK^^
anyway, thanks everybody!

**Comment by enricorov** [comment]
![immagine](https://cloud.githubusercontent.com/assets/23199149/19942469/1cb57a46-a134-11e6-94fe-d5a1c51da62e.png)

Doing some more testing, the graph looks more like this.

**Comment by enricorov** [comment]
It's up to you to choose a box, the VTwo is really nice, but I don't have any other for comparison.

**Comment by afol2** [comment]
Ok, im trying to do that on my Cuboid, but the NFirmwareEditor its saying "No Compatible USB Devices conected" Mod is in COM and NFE is On

**Comment by ClockSelect** [comment]
@enricorov VTwo looks like a good TC vaping mod.

**Comment by ClockSelect** [comment]
@afol2: Use the usual procedure. Close everything, reset everything.

**Comment by falconettt** [comment]
@afol2: if you are on win7 you need a driver, try to find it/

**Comment by ClockSelect** [comment]
There is a driver directory in the repo.
[Here.](https://github.com/ClockSelect/myevic/tree/master/driver)

**Comment by afol2** [comment]
@falconettt yes window 7

**Comment by falconettt** [comment]
@afol2: take it...
https://yadi.sk/d/R3-2wKchxzB8q

**Comment by afol2** [comment]
@falconettt thanks.!

**Comment by falconettt** [comment]
@afol2:
use here:
![123](https://cloud.githubusercontent.com/assets/22370680/19943407/4bff565a-a148-11e6-8183-5954aa5e1095.jpg)

**Comment by falconettt** [comment]
So, let it be eVic VTwo Mini...
