### ISSUE TITLE
my rx2/3 cant connect to NFE device configuration or device monitor

### ISSUE THREAD

**Issue by RenegadeTitan** [ClockSelect/myevic#119]
i saw that you posted a live readout of an rx2/3 firing so i assume im missing something. my rx2/3 is recognized while expert setting usb is set to pid. NFE says i need to enable vcom and this changes usb setting from pid to com. at this point NFE no longer recognizes my device. i saw u had links to what looked like mac virtual com drivers. do i need a windows virtual com driver for my pc or something? (running windows 7) what am i missing?
(i tried firmware newest myevic.bin directly from you github bin and myevic_161030 NFE edition) could not tell if i needed the nfe edition or if your github version supports it. i dont speak russian :)

**Comment by Daveee10** [comment]
Try to turn Off the UCH...

**Comment by StepWi** [comment]
And make shure NFE is ON in Expert Menu.

**Comment by RenegadeTitan** [comment]
thank you for your responses. i already tried both of those and just tried it again to no avail. im using the myevic.bin directly from this github. does that firmware support device monitor?

**Comment by RenegadeTitan** [comment]
i also tried clearing dataflash and reinstalling. i believe NFE on enables com mode similar to how USB com does. when either one of these is enabled NFE program says no compatable usb device detected.

**Comment by TBXin** [comment]
Hello,

Your are missing VCOM driver for Windows. You can get it in this rep ;)

**Comment by ClockSelect** [comment]
Thanks @TBXin
