### ISSUE TITLE
Feature request: Display third line on screen saver and charge screens

### ISSUE THREAD

**Issue by eugenesan** [ClockSelect/myevic#12]
It would be useful to see third line also on screen saver and charge screens in order to inspect Battery Voltage or Board Temperature.

**Comment by ClockSelect** [comment]
Just click fire button... no?

**Comment by eugenesan** [comment]
Clicking Fire button will work but seeing the numbers passively would be nice.
The screen is mostly blank anyway and is constantly updated with Clock/Logo/3DCube/BatteryLevel so adding that feature should not affect battery life while providing useful information.

**Comment by ClockSelect** [comment]
Keeping it mostly blank is precisely the purpose of a screen saver^^
And we would loose some aestethics.

**Comment by Daveee10** [comment]
IMHO the battery voltage and temp is a good idea on charging screen top of the battery indicator...
Another thing. The logo not working. Is this just for me or this is a real issue?

**Comment by ClockSelect** [comment]
If you're charching, you should have the charging screen - blank with batt at the bottom.

Logo should work; I have it fine. Tell me more.

**Comment by ClockSelect** [comment]
When charging, battery voltage is always 4.2V, so... It's a bit useless.
Why would you want the temperature?

**Comment by eugenesan** [comment]
I just checked, BatteryVoltage in 3rd line is showing actual voltage of the battery and not constant 4.2 volt.
Regarding the temperature, since Lithium cells are better charged when cold, it's useful to know how hot the device is to minimize battery wear.

P.S. The Logo is working fine here.
I've uploaded it with: `evic-usb upload-logo logox.bmp` and made sure it enabled in: `Menu->Miscs->LOGO`

**Comment by Daveee10** [comment]
I'm trying with NFirmwareEditor and Joyetech's original firmware updater, but logo not works..
My HW version is 1.00 with SSD1306 display. I try to find the problem and solution but i can't found.

**Comment by ClockSelect** [comment]
Give a try to the new charge screen. Made it simple.

**Comment by ClockSelect** [comment]
A specific issue has been opened for Logo problem.

**Comment by eugenesan** [comment]
Great, the issue is solved.
Thanks a lot!
