### ISSUE TITLE
Voltage shown in Bypass Mode

### ISSUE THREAD

**Issue by cblag13** [ClockSelect/myevic#120]
I'm using an **Evic VTC Mini**, dual twisted Clapton coils, **0.34 ohms**.
Don't know if this is an issue or I didn't fully understand how it works, but...
In **Bypass Mode**, the first line voltage is **3.06V**, even though the battery voltage is **3.65V**. Also, the power, displayed on the top of the screen, is **27.5W** (instead of **39.1W**, how it should be at 3.65V). 
So...why?

**Comment by ClockSelect** [comment]
If your battery shows 3.65V, you can't send 3.65V to the atomizer. You have to take into account the internal resistance of the battery, and the efficiency of the circuits. The displayed voltage/power is a predictive value; maybe not perfectly accurate, but far more than the raw values derived from sole battery voltage.
When you actually fire, what does it says?

**Comment by cblag13** [comment]
For example, now (in Bypass Mode) the battery voltage is **4.17V**, the voltage shown in the first line is **3.74V**, the top screen wattage is **41.1W** and when I press the fire button, the wattage shown is between **39.2 - 39.6W**. The wattage at **4.17V** should be **51.2W** (hypothetical, leaving aside the internal resistance). It's kind of a big difference

**Comment by ClockSelect** [comment]
_"leaving aside the internal resistance"_...

The **41.1W** is a fairly good approximation of the given **39.6W**.
Would you prefer that I display **51.2W** and give you **39.6W** like the stock firmware does?

Bypass mode is a WIGIWYG system (What You Get Is What You Get).
You cannot leave the internal resistance aside if you want to estimate what you'll get.

**Comment by cblag13** [comment]
Ok, that sorts things out. Thank you
