### ISSUE TITLE
Battery % vs. Voltage

### ISSUE THREAD

**Issue by ghost** [ClockSelect/myevic#126]
Hi, 

First of all, thank you for this great mod. It's really fun to play with! 

I'm not sure what is causing it, but I think the battery % doesn't act like it should. It will stick around 60% from 3.8 to 3.7 Volt, then fall rapidly.

Do we have to calibrate the battery in some way? I didn't want to mess with the expert settings since I don't know the battery model inside. I'm using the Cuboid Mini. 

Best regards

**Comment by StepWi** [comment]
It is very difficult or often nearly impossible to calculate the State of Charge (SOC) of a Lipo depending on the voltage of a cell. The cell in the cuboid mini isn't  changeable, and afaik of unkown type, so probably nobody knows the relation between cell voltage and SOC.
I have a similar "problem", it is showing 100% most of the time, even at 4.1V. I have set battery type to GEN(eric) in expert menu. I live with that limitation.
The only way to change behaviour is to calculate the integral of used mAh and compare it with the nominal capacity of the cell. But if cell is aging this calculation would be probably worse compared to the actual solution, or after discharge the nominal capacity has to be corrected to the calculated integral of used mAh.

**Comment by ClockSelect** [comment]
Boxes like Cuboid Mini with built-in battery have their own discharge curves.
They are not yet handled by the firmware; it will come soon.

**Comment by ghost** [comment]
Thanks for the answer. Looking forward!

**Comment by ClockSelect** [comment]
Done.

**Comment by ghost** [comment]
Cool! I'll leave this open and report as soon as I can :)

**Comment by ClockSelect** [comment]
No news, good news.
