### ISSUE TITLE
base ohm reading 

### ISSUE THREAD

**Issue by RenegadeTitan** [ClockSelect/myevic#127]
any chance the base ohm reading could be extended an extra digit to thousandths of ohm in coil settings instead of hundredths of ohm? i believe this would help a lot in calibrating displayed temperature readings and to a lesser extent slightly increase accuracy of temp control regulation and algo pid adjustments. my current coil is .096 ohms and when locked in at .10 it requires 350f setting to fire correctly or locked in at .09 requires 520f setting to fire correctly. quite a wide range for closest options to actual ohms. i see option in nfe configuration for setting thousandths of ohms. im having an issue uploading any changes made in nfe to my device. this is a separate issue and i will experiment before opening new issue for that.

**Comment by ClockSelect** [comment]
Assuming TCR=120 and Rreal=0.096Ω,
In the first case (0.100Ω, 350°F) your target rez is 0.115Ω (185°C/365°F)
In second case (0.090Ω, 520°F) your target rez is 0.117Ω (214°C/418°F)
It's a bit different but let's assume you really want 200°C (392°F), we're around a target rez of 0.116Ω.
You want the rez to be 0.116Ω when T° shows 200°C
Say you lock your rez at 0.090Ω (better lower, avoid sub-zero temps).
You should be good by setting your TCR around 160.

Ok, it's a workaround.
But I must see what your change implies - rez are used everywhere in calculations and it's easy to forget something somewhere.

Problem in your case is that you use very low sub-ohm coils with low a TCR metal; combination of the two gives temp control a very high milliohm sensitivity (around 10~15°F/mΩ).

**Comment by ClockSelect** [comment]
SS316L, 0.75Ω, RX200S, 75W

Before (10mΩ accuracy):
![](https://www.dropbox.com/s/iri7b378hzgnn28/monrxmilli1.png?dl=1)

After (1mΩ accuracy):
![](https://www.dropbox.com/s/1b8dzcotui0jr0j/monrxmilli2.png?dl=1)

Seems there's a little gain in temp stability, but that's not obvious with my setup (0.75Ω, I'm far from your needs).
Anyways, it works.

**Comment by ClockSelect** [comment]
Give it a try.

**Comment by RenegadeTitan** [comment]
@ClockSelect i went back and forth between firmwares about 15 times each relocking base resistance at .09 @ 520 degrees and .096 @ 420-430. seems to be nearly identical fluctuations as it regulates (on further thought seems it should not make a difference in functionality as long as you avoid higher ohm locked in than actual coil). possibly slight improvement but dont see how it would(again referring to functionality of regulation). one noticed behavior that i do not understand is that when on .01 accuracy firmware i lock resistance to .10 then immediately to .09 to remove any previous set base resistance. performed test. then flash to .001 accuracy firmware (again) and .096 is automatically showing as locked (even if coil is warm and still above this) so it appears it is somehow pulling this from memory. maybe you used a different memory location/variable to function as displayed base ohm reading? not an issue just found it interesting. 

as far as accuracy of displayed temperature this is greatly improved (through the entire range from 70-vape temp). allows much more room for calibrating lower ohm coils. mostly an aesthetic improvement but one that i enjoy a lot. i think this is a significant improvement. thank you once again :)

**Comment by ClockSelect** [comment]
In fact, the "0.09" is stored as usual and the "6" elsewhere. Problem with dataflash is that if you wish to modify its data structure, you can only do so incrementaly, conserving content and meaning of previous locations, to allow compatibility between firmwares and versions of firmwares. Except if you accept a dataflash reset at some point.

**Comment by RenegadeTitan** [comment]
small idea, maybe since most coils are under an ohm display on main screen .xxx accuracy unless over 1.00 ohm then display x.xx accuracy?  just an idea for if your looking for something to do :)

**Comment by ClockSelect** [comment]
That's indeed an idea.

**Comment by ClockSelect** [comment]
Here's what you should get if the resistance reading was less noisy (VTC Dual); you can compare with graphes above:
![](https://www.dropbox.com/s/t6h6qpjr06c9kf3/mondualpid.png?dl=1)

**Comment by RenegadeTitan** [comment]
i thought live readings of coils were already .001 accuracy and compared to .01 accuracy of base resistance to get a .001 accuracy change. wouldnt this have same regulation?

**Comment by RenegadeTitan** [comment]
comparing the 2 devices, what causes the noisy ohm reading, circuitry or 5/10?

that vtc dual is quite stable lol

**Comment by ClockSelect** [comment]
Hm... Seems you're right. I'll cancel my previous comment.

Can't be 100% sure, but say 99% for circuitry. I have the same result with an RX that had his 510 replaced.

**Comment by t2dYuri** [comment]
@ClockSelect thanks for the update. For now, i have locked 0.73Ω in the second row of main screen, and 0.739Ω in the coils management menu. I understand, that it's just visual differences, but may be it would better to observe the same value in both places?

**Comment by RenegadeTitan** [comment]
:)

**Comment by ClockSelect** [comment]
That was the point of 7 comments above^^

**Comment by RenegadeTitan** [comment]
hey clockselect while your here mind if i ask you about nfe updater? i can pull info from device but cant upload changes to device. any ideas?

**Comment by ClockSelect** [comment]
The configurator of the NFE is meant to be used with the NFE Edition of the firmware (an independant russian fork); your dataflash are not compatible. Maybe we'll do something for that in the future.

**Comment by ClockSelect** [comment]
Display adapted.

**Comment by RenegadeTitan** [comment]
ok thanks. i already removed that question and reposted as new issue. i posted it on nfe site also.

live display of milliohms looks good
