### ISSUE TITLE
Feature request: Rename "Screen Protector" to "Screen Saver"

### ISSUE THREAD

**Issue by eugenesan** [ClockSelect/myevic#13]
I believe "Screen Saver" is a better alternative "Screen Protector" and will avoid confusion with "Temperature Protection".

**Comment by ClockSelect** [comment]
"Screen Protection" is the way it's referred to in Joyetech's manual, that's why I choosed this menu title. I try to stay the closest possible to what regular box users are used to.

**Comment by eugenesan** [comment]
I see, in that case it's fine with me.
Thanks.
