### ISSUE TITLE
nfe device configuration modifying data

### ISSUE THREAD

**Issue by RenegadeTitan** [ClockSelect/myevic#130]
using rx2/3. this may be more appropriate for nfe page but perhaps you can help. in nfe device configuration i can download most info but changes made in nfe do not change on device even though upload says it is successful. i tested temperature and base ohm. any ideas?

**Comment by ClockSelect** [comment]
The configurator of the NFE is meant to be used with the NFE Edition of the firmware (an independant russian fork); our dataflash are not compatible. Maybe we'll do something for that in the future.
