### ISSUE TITLE
PID algo

### ISSUE THREAD

**Issue by RenegadeTitan** [ClockSelect/myevic#132]
just started messing with this but based on what i have read about calibrating pid this may have been source of previously reported +35 degree (f) high temp regulation with default settings when in pid algo that i encountered. when doing trial and error calibration to p with i=0 and d=0 i am unable to get device to hit temp even with p=2000. it seems to reduce wattage before achieving temp regardless of p setting. even at max setting it slowly approaches below temp over 2-3 seconds but most importantly does not produce an oscillation. my understanding from reading is that with i=0 and d=0 p should be increased until oscillations begin to occur and then i is slowly increased to remove these. maybe p is missing x10 modifier? what is boost setting doing and is that a modifier to one or all of pid settings? maybe p is calculating based on (temp setting - x) to avoid overshoot? i have 30 minutes total of knowledge/experience with anything pid related so as a fair warning i do not know what i am talking about yet lol. 

i could not find discussion of your pid algo so was hoping you could help me understand your implementation of it so that i could use it more effectively.

note: "i" setting seems to behave differently than i anticipated as well. could be cause for "p" behavior. i will post more when i understand behavior better.

**Comment by ClockSelect** [comment]
The P-only can never stabilize or oscillate around the target temperature; this is a property of P regulation. It stabilizes or oscillate around a value with an offset below the target. It's the role of the Intergral part to fill the gap between the P offset and the target.
You're trying to use the ZN method; it may work but it takes some time as a trial-and-error method.
I used a more procedural method described [here](http://controlguru.com/table-of-contents/).
How does the default value behave with your setup?
Just try doubling or tripling them on an heavy setup.
Also, the Device Monitor of the NFE is a very handy tool to tune the PID.

**Comment by ClockSelect** [comment]
In the doc, I give you the units of the parameters. As you can read, P in in mW/°C; it means that the PID will command a power of P \* ( temp diff ) mW. If P=600 (default) and you want to up temp by 180°C, it will set the power to 600*180mW = 108W (at first). You may need more to get a fast ramp-up with your setting; go to the 250W and try to set P=1400. Increase I accordingly, so I=2000.
This should do the job.

**Comment by RenegadeTitan** [comment]
still messing with pid settings. seems maxed out P and lower I gets me closest. adding small D seems to help. here are screenshots:

algo off:
![clean_off_default](https://cloud.githubusercontent.com/assets/20567674/20026774/663205fa-a2be-11e6-8677-92a4100ae541.jpg)

default algo pid:
![pid_default](https://cloud.githubusercontent.com/assets/20567674/20026786/a2d72d8c-a2be-11e6-9240-7f446b80f95b.jpg)

**Comment by RenegadeTitan** [comment]
PID P=1400 I=2000 D=0 (boost 0%)
![pid_p1400_i2000_d0](https://cloud.githubusercontent.com/assets/20567674/20026890/aee9d608-a2c1-11e6-8504-da2b54836c5f.jpg)
:

**Comment by RenegadeTitan** [comment]
@ClockSelect i think i closed this unintentionally. if you closed it no problem. ill figure it out. just brought up PID because it seemed like strange behavior. its most likely something im not doing right. too much nicotine after all this testing cant think straight lol.

**Comment by ClockSelect** [comment]
You keep your max power setting too low.
Using PID, you don't care what your max power setting is; just set it at 250W and forget it. The PID will just take what it needs. You're not leaving enough power to the PID to give you a good ramp-up.

About Boost: it's used for the Boost algorithm. Useless for PID.

**Comment by RenegadeTitan** [comment]
appologies, i misunderstood first reference to 250w. im using 2 battery configuration so tested at 200w. yes that works much better. thank you. that made it fire very close to same as PID off.

considering 120w is adequate for other algo modes, and i prefer to not use more than this ever (typically use 2 battery configuration) to avoid 20a draw from low batteries, is there an increased range of one or all of PID values that would help? i assume other algo modes use similar core calculations to PI or PID method, what is reason 120w is functional in algo off versus algo pid? increased D value? or do those modes regulate temperature with vastly different method?

**Comment by ClockSelect** [comment]
Methods are different.

The Boost algo works similar to Joyetech's , except it considers different phases in the puff (ramp-up, stabilization, regulation...) and behaves differently in differents phases. The boost parameter is used to accelerate the ramp-up phase; the heaviest the build, the higher you should set it (maybe 80% in your case). It may work well in your case.
The Sweet algo is more or less a simplified zero Boost. It dampens oscillations on light builds.

For PID:
Don't bother with the **D**. It brings very little improvement if any.
If you limit the available power, you should decrease **I** to avoid the long overshoot you see on your curves, since the integral builds up during a longer time.
You'd better use 3 cells with your setup, and unconstrain the PID.

**Comment by ClockSelect** [comment]
I added a battery protection in the PID algo; you can safely set your power to max and the box will adjust its max power depending on the battery state-of-charge. It will not draw more than the rated continuous discharge current for the selected battery model.

**Comment by RenegadeTitan** [comment]
please forgive my slow posting in this thread, i am still playing with this whole area and require more time to develop productive ideas.

it is a good idea but i am concerned by any additional limitations that are not editable/adjustable. are the limits based on rated amp limits or tested amp limits? i have not seen a 18650 actually test over 23a and most/all 18650 will incur some level of damage at 20a even if "rated" at 25a/30a. also this would cause vapes to change as battery charge/voltage lowers. also i find most limits restrictive as they limit my options.

i would prefer a less restrictive solution if we can find one. 

i am getting very different results depending on starting coil temperature due to differences in time required to reach set temp (same cause affecting the set wattage at 120w vs 200/250w different results, time to reach temp causing huge variances in regulation). it is my opinion that set wattage should be applied to achieve temp then regulation maintains it. what if instead of amp limit on batteries there was a function that applies set wattage until actual temp reaches >= (set temp -x) then starts pid algo  (x could be 10 or 20 degrees or possibly settable by user)? this would make every vape very consistent regardless of starting temp or set wattage as long as set wattage is above wattage required to maintain temp. and users could still choose to push batteries up to 25a (already built into device limit i believe) if they are not concerned with length of battery life.

**Comment by RenegadeTitan** [comment]
unrelated, just showing off current my build :) SS316L twisted 24awg core wrapped in 30awg 4.5 wrap 5mm id dual coil .097ohm:
![20161027_132851](https://cloud.githubusercontent.com/assets/20567674/20113699/b98fb2fe-a5ae-11e6-9bf1-82d7c750bdfa.jpg)
 colors mostly went away after working out hotspots.

**Comment by ClockSelect** [comment]
Applying the set wattage until reaching target temp is what the PID algo does if you give it a lower-than-max power; if you look at your curves, it's exactly what happens (except that there's some overshoot due to integral action, but that's tunable whith the parameters).

The high-current heating phase is very short if you give the algo the full power range; it's a ramp-up spike that lasts less than a second, and batteries can handle this kind of spike fairly well. I use Mooch's chart to define what the max Amps should be for a given battery model; he made reliable testing on batteries and my settings are not too conservative albeit safe for the cell. Anyway, at high Amps, you're limited by the internal resistance and the voltage sag that would drive voltage under the 2.8V limit, and thoses limits are close to each other so it's not really a limiting factor.

With near depleted battery, it's the 2.8V limit that takes precedence and the max Amps cannot be achieved anyway (the box would shut down), so there's no real concern with battery stress.

So you can safely set your power to the max allowed by the box and forget it; the algorithm will use what it needs and perform at its best.

Nice heavy build :)
I just ordered some SS staggered fused clapton to experiment with this kind of stuff.

**Comment by RenegadeTitan** [comment]
thanks! i make the claptons myself with a drill and clapton rig i made out of a clothespin. but fused are 3x the work to make so probably better to just purchase them. i want to try those. i think they may work the best of any coil type. imo any ss coil is better than any coil of other material. enjoy :)

thumbs up to everything in last post, you relieved all concerns i had. good to know i can set watts to max and it will be fine.

i do still prefer to have the option for setting watts lower than max. i will try different PID settings for this. still experimenting. i do still think an option for adjusting the PID kick in point could be a good idea but now that i know there is a kick in point ill play around and see if that factors in much/at all.

**Comment by RenegadeTitan** [comment]
i just noticed P max setting was dramatically increased from previous limit of 2000. that was one theory i had as to possible cause. thumbs up again. ill keep playing around.

yep! dramatic improvement so far. good call on increasing it. PID mode with 3000 P everything else default is already better for me/this coil than algo off mode. havent even started tweaking P or rest of settings yet. and im still at 120w setting.

**Comment by ClockSelect** [comment]
**P** is in mW/°C, that means the controller will drive the power to P*δT mW, where δT is the wanted increase in temperature. So even with 250W available you should never need more than ~1400. Higher values won't accelerate the ramp-up and will increase instability.
Maybe it was not a so good idea to increase the limit; we'll see.

**Comment by RenegadeTitan** [comment]
ramp up was adequate at 1400 but was overshooting. this was source of overshoot. it is now adjusting faster and not overshooting. device is still limited by wattage setting as it should so i believe calculating propper P setting based on max wattage is incorrect. P set too high will never exceed this. the concern shouldnt be that P creates too high a wattage at large distance from set temperature as PID does not function at great distance from set temperature. concern should be that P creates high enough wattage change at medium/small distances from set temperature to regulate fast enough. this seems perfect :) higher than 6000 may even appropriate.

**Comment by RenegadeTitan** [comment]
you may be working on firmware but i wanted to mention that i dont see the bin folder.

**Comment by ClockSelect** [comment]
bin came back :)
messed up during a pull request.

**Comment by RenegadeTitan** [comment]
phew! all is right with the world again :)

**Comment by RenegadeTitan** [comment]
i havent played with settings yet but compared with algo off its already great. plus i was starting to get major oscillations intermittently with algo off so now i can stop troubleshooting that lol.
P=3000 I=850 D=0 :
![pid_p3000_i850_d0](https://cloud.githubusercontent.com/assets/20567674/20120217/2bf4bb18-a5c9-11e6-8d77-030dbbfcf4ed.jpg)

**Comment by ClockSelect** [comment]
That seems not bad at all.
You still limit yourself to 120W.
How does it behave if you unleash the horses?

**Comment by RenegadeTitan** [comment]
same settings with 200w gave small overshoot but with quick wattage adjustments so likely not P issue. very unexpected.
![pid_p3000_i850_d0_200w](https://cloud.githubusercontent.com/assets/20567674/20121092/deb8bde6-a5cc-11e6-990b-7a5cf7d7d144.jpg)
lowered I to 700 and got this:
P=3000 I=700 D=0 200w :
![pid_p3000_i700_d0_200w](https://cloud.githubusercontent.com/assets/20567674/20120974/58501ccc-a5cc-11e6-8134-c003cb1c6837.jpg)
i bet I~600 would be even better. have to pace out tests, too much nicotine lol.

**Comment by ClockSelect** [comment]
Looks not very far from the best achievable :)
Maybe still too much of **I**, indeed.
@ 200W, your fastest theorical ramp-up is around 0.75s; we're close.

**Comment by RenegadeTitan** [comment]
i agree. slope of line to set temp is almost consistent. as far as regulation at temp i think at perfect settings all bumps could possibly be size of first 2 bumps. but just an estimate based on accuracy of ohm readings. looks good so far :)

**Comment by RenegadeTitan** [comment]
quick question, well may not be a quick answer lol, does set wattage affect any PID calculations that would directly affect temperature regulated wattage output? (other than slow warm up causing exagerated PID calculations before reaching temp)

**Comment by ClockSelect** [comment]
Yes and no.
If you lower the wattage, ramp-up will take longer, so error integral will have more time to build up and ultimately generate an overshoot and oscillations. So if you lower the wattage, you have to lower the **I** accordingly to prevent those adverse effects.
Beyond that, it has no influence.

**Comment by RenegadeTitan** [comment]
ok cool. thats all making sense.

so heres what im thinking:
the temperature each vape starts at varies due to time from end of previous vape (causing different starting temperatures) which would cause different PID calculations (I increasing by different amounts each vape). you have reduced this effect with the PID only kicking in closer to set temperature after applying set wattage to reach this temperature point. so far so good (EDIT: or maybe you didnt implement this and i misunderstood. normal algo off uses this and ramp up [specifically right before reaching set temp] temperature increase is a straight line, not curve ). but i am still noticing a variance in performance with more frequent vaping and a strong curve at the top of warming up phase that starts relatively low with some PID settings (probably just above PID kick in temp). i think raising the PID kick in temperature point even further (closer to set temperature)(and above potential subsequent vape starting temperatures) would further improve consistency. the closer to set temperature the better except that too close and PID will not kick in before overshoot. kick in point before overshoot varies based on coil and set wattage resulting in a specific ideal PID kick in temperature point. i propose, if not too much trouble, making the PID kick in point (degrees below set temperature) adjustable. maybe in algo menu in place of boost% setting while algo=pid?

EDIT: i think this will work as of now but i am not positive this is the best solution. i have a pretty good handle on PID but i still do not have an expertise in its function. my calculus is very rusty.

**Comment by ClockSelect** [comment]
The PID applies from start. There's no such thing like waiting for a target temp, or kick in point. Just, the max power it can apply is clamped so it's constrained on a straight line.
If it starts on a warm coils, it'll just apply less power to ramp up since Pwr=**P**xδT+**I**xΣδT, and δT is smaller. If you consider the extreme case, imagine you're firing while coil is already at target temp, the PID will apply just no power at all, and that's you'd expect.
Integral part does build up more slowly and has less effect on an already warm coil, so the convergence to target temp is slowed down, and maybe it's what you feel. You can increase **I** to counter this, but at the cost of a potential slight overshoot on cold coils. PID is always a question of compromises.
Best thing would be to increase the available power to 250W with a third cell, so that you can increase **I** without overshooting on cold coil, and keep a good behavior on warm coils. After all, your build is not really made for dual-cell.

**Comment by ClockSelect** [comment]
I think the new profile feature will come handy when you'll have multiple atomizers with each of them having their own tuned PID parameters^^

**Comment by RenegadeTitan** [comment]
cool. thats a nice addition. thank you.
also i appreciate that you take the time to understand my wordy, complicated posts and give such thought out and detailed responses.

**Comment by RenegadeTitan** [comment]
i would like to mess around with with the algo functions (assuming you dont mind me experimenting) and try to impliment an idea im working on. i have little to no experience with c. but i was very proficient with hyper logo on the ti-84 a long time ago. i wrote some games and physics examples. c is actually pretty similar (at least structurally). but im getting really hung up on setting up cygwin with various additions for compiling in windows. im following ReservedField's evic-sdk instructions and gleaming a little info from your notes in your makefile. keep getting different errors. any help in simplifying the process of compiling would be appreciated so i can focus my efforts on the code itself.

**Comment by ClockSelect** [comment]
In fact I just followed instructions from eVic-SDK to setup my environment and it worked just fine. Made no change to the env since.
So I can hardly give you any advice without some more informations.
I suggest you to open a separate issue for this; so everybody can come to help.

**Comment by RenegadeTitan** [comment]
great! thank you for clarifying for me that i can just follow those instructions. i will keep trying to fix errors as they come up and if i get a little stuck ill open a thread. i expect to open a thread soon lol.

**Comment by sandbagjohnny** [comment]
@ClockSelect Thank you for this info! [I've posted an essay/mini-review of the new temp control methods on reddit](https://www.reddit.com/r/electronic_cigarette/comments/5ql2kn/on_pi_regulation_and_arcticfoxmyevic_some_notes/) based on both your comments here, and [maelstrom's comments on PI in his fork](https://github.com/maelstrom2001/ArcticFox/issues/91)

**Comment by ClockSelect** [comment]
@sandbagjohnny How can't you have a myevic-compatible box? ^^

You're right on your analyzis, the PI-regulator of ArcticFox is best suited to high-end heavy coils builds with its defaults values. But both act well with the correct parameters, and you can convert parameters from one to the other. There is no real difference between the two, except the intented audience.^^

**Comment by sandbagjohnny** [comment]
Thanks :) I've cleaned up the essay a little bit to reflect this, as I agree, both packages have their own unique style, and I've heard as many positive reviews of your offering as I have of AF. Thanks for your contributions!!
