### ISSUE TITLE
Feature: Add "PPwr behavior" for preheat in Power Mode

### ISSUE THREAD

**Issue by phantasm** [ClockSelect/myevic#133]
In TC mode we have a great ability to quickly switch between Temp and Power limits (if PPwr mode is enabled).

It will be awesome if the same feature will be able to work in Power mode, switching between main power setting and preheat power (maybe with preheat duration, too). What do you think?

**Comment by ClockSelect** [comment]
Why not.
It's question of interface design; I can't see how I'd do a user-friendly thing.
Maybe just using the PPwr click shortcut in PWR mode, if you defined one, sends you is the preheat menu? Simplest option.

**Comment by phantasm** [comment]
@ClockSelect  that's exactly what I mean :) if PPwr click will switch between main power, preheat power and duration, it will be great.

**Comment by ClockSelect** [comment]
That some code.
I though bringing you straight into the preheat menu.
Or maybe just switching preheat on/off would be enough?
Once your coil is hot, you don't really need preheat at all. If it colds down, click and preheat again.

**Comment by phantasm** [comment]
@ClockSelect preheat menu will be good too, but it's harder to switch back to main screen, because you need to use +/- buttons and several clicks.

I think that quick switching preheat mode on/off is pretty useless, because usually you want to fine tune your preheat settings for the coil, not turning it off :)

**Comment by ClockSelect** [comment]
Fire-(+) gets out out of menus back to main screen instantly.

**Comment by phantasm** [comment]
@ClockSelect oh, indeed :)

**Comment by ClockSelect** [comment]
Try this.

**Comment by phantasm** [comment]
@ClockSelect seems to work nicely on my RX2/3 so far
