### ISSUE TITLE
#133 evic off can open preheat menu

### ISSUE THREAD

**Issue by mrnonaki** [ClockSelect/myevic#136]
I set ppwr in 4click and turn off the box but I can open ppwr menu in 4click. Is it bug.

**Comment by ClockSelect** [comment]
Indeed :)

**Comment by ClockSelect** [comment]
Fixed, thanks.

**Comment by mrnonaki** [comment]
oh,  I found in keylock too it can use multi click

**Comment by mrnonaki** [comment]
or keylock only + - ?

**Comment by ClockSelect** [comment]
Yes, keylock concerns only + and - keys.
