### ISSUE TITLE
Interface lag?

### ISSUE THREAD

**Issue by phantasm** [ClockSelect/myevic#137]
When navigating through the interface, some strange things can occur - menu items are skipped, etc. Maybe it's related to board performance, but maybe it's a bug. It's definitely not related to button jitter -  I've verified it with various click speeds and thumb force.

Video: https://www.youtube.com/watch?v=YYXHNVZuBDk

Firmware: Any recent
Box Model: RX2/3

**Comment by ClockSelect** [comment]
Buttons are polled at 5Hz; if you're clicking to fast, you're interfering with the polling frequency and the box goes into key repeat mode and accelerate, thus going faster than the display refresh rate (10Hz max).

**Comment by phantasm** [comment]
@ClockSelect maybe increase polling rate when in menu mode? It won't eat too much battery (because you don't open menu too often), but will be a lot smoother.

When in main screen, you don't miss too much - for example, instead of +1W, you'll get +2W. But when navigating through the menu, it's more disturbing because you can miss the desired menu item.

**Comment by RenegadeTitan** [comment]
i have experienced same behavior. if  polling of 10Hz is possible this may allow for fast clicking. i dont think more than 10 clicks/second will be common enough to be an issue but i belive 6 or 7+ clicks per second is relatively common even in menu navigation.

**Comment by ClockSelect** [comment]
Let's test 10Hz.

**Comment by phantasm** [comment]
@ClockSelect now it's much, much better, thank you! hope that polling is increased only in menu mode and will not eat battery.

**Comment by ClockSelect** [comment]
This kind of change does not impact battery consumption at all.
