### ISSUE TITLE
PreheatDelay masks under-load battery voltage display

### ISSUE THREAD

**Issue by MarkusAD** [ClockSelect/myevic#139]
Box Model: VTwo mini/VTC mini

Without PreheatDelay, it is possible to see the under-load battery voltage just after taking a puff. When enabled it masks displaying it, so that by the time the display gets refreshed, the battery has already returned to its no-load voltage. Thanks for all the updates, features and fixes.

**Comment by MarkusAD** [comment]
Its not that the display isn't refreshed soon enough, but rather too soon. If it waits until the onscreen puff timer disappears, that gives enough time to see what the voltage under load was. Increasing the value in timers.c which tests for ! (--PreheatDelay % 25) avoids the issue but then the P doesnt blink often enough.

**Comment by ClockSelect** [comment]
I see.

**Comment by ClockSelect** [comment]
Fixed.

**Comment by MarkusAD** [comment]
Nice work once again. Fixed and closed.
