### ISSUE TITLE
Which battery slot is which on RX200s?

### ISSUE THREAD

**Issue by SIimJim** [ClockSelect/myevic#142]
**Box Model:** RX200s

Hi Guys Amazing work!!!
Quick question I am trying to set the correct voltages for my batteries but I am getting differnt readings in device (RX200s) compared to  my multimeter and I just need to know which slot is which, my instinct tells me looking at the back of the device the left inner battery is 1 right inner battery is 2 and the center outer battery is 3 but things just don't seem to add up please advise :) thanks again for your amazing work I literally LOVE it :)

**Comment by bluenazgul** [comment]
Seen from Display Side:

   3
2   1

**Comment by SIimJim** [comment]
ok great just like I thought :)

**Comment by ClockSelect** [comment]
@bluenazgul  Hm... Seems that's the layout of the RX2/3.

RX200S would be:

 2
3 1
---
^display

**Comment by bluenazgul** [comment]
@ClockSelect This is the only Layout i found for the RX2/3 - I think RX2/3 and RX200S should be the same, needs to be verified with two full charged and one empty Battery i think

![wismec-reuleaux-rx-23-akkufach-anzeigeposition-display](https://cloud.githubusercontent.com/assets/171537/20065702/52a01880-a50f-11e6-9748-a1492c2b3e21.jpg)

**Comment by SIimJim** [comment]
You know what, that is such an easy way to test it I feel dumb haha I will have to go get my Koopor Mini out the car to run a battery down :) I will post results asap

**Comment by ClockSelect** [comment]
That's what I did, once^^
But just by looking at battery polarities, you find out the current path and wich one is wich.
The rearest battery in the RX200S is the number 2.

**Comment by SIimJim** [comment]
So is this confirmed in the RX200s?

2
3 1
^display

**Comment by ClockSelect** [comment]
Yes.

**Comment by ClockSelect** [comment]
Btw, if you short the connectors of the third battery (left inner), the RX220S will perfectly work as a dual-cell box just like the RX2/3 (tested, works). It's a bit useless since you have to keep the number 2 and thus cannot reduce the size of the box, but it's a curiosity.

**Comment by SIimJim** [comment]
Haha cool, well thank you very much for the help and myevic in general 👍
