### ISSUE TITLE
Choose date style

### ISSUE THREAD

**Issue by Stofkri** [ClockSelect/myevic#149]
Hello,
Is it possible to add a menu to choose the date style?
example: D.M.Y or D/M/Y and M.D.Y or M/D/Y
Because in my country the date is displayed with "/" and not "."
Thank you

**Comment by ClockSelect** [comment]
Everybody should be happy.

**Comment by enricorov** [comment]
I like the date as DD.MM.YYYY, I think it offers the best readability.

Il mer 9 nov 2016, 14:52 ClockSelect notifications@github.com ha scritto:

**Comment by Stofkri** [comment]
thanks
