### ISSUE TITLE
request please

### ISSUE THREAD

**Issue by FlorinDiablo** [ClockSelect/myevic#152]
Hi,

Could you please help me to remove intuitiv bare for counting vape second?
Tnx!

**Comment by ClockSelect** [comment]
I'm afraid I don't understand the question... ?

**Comment by Daveee10** [comment]
I think he mean the Pico style puff timer bar.. Maybe he want to switch off/change back to original style.. Correct me if I'm wrong... I don't understand why not good the new bar... IMO more eye friendly..

**Comment by RenegadeTitan** [comment]
my guess is he cant find option for not displaying this bar
i dont think my device has this option so i cant help

**Comment by ClockSelect** [comment]
Puff timing is a legacy of old mods. Its usefullness is highly questionable. But if I remove it, I'll get two issues tomorrow asking how they can restore it. And I don't want to spend a config memory for that. I'll keep that for a later revamp of screen display; for now, I'll keep things as they are.
