### ISSUE TITLE
Icons instead of Text

### ISSUE THREAD

**Issue by MoDuLah** [ClockSelect/myevic#154]
**Box Model:**
Evic VTC Mini
**Coil setup:**
Nife48, 28mm @0.63Ω

Back in the stock firmware i used to make some text swap and display icons instead of text for coil/power/puffs/ohms etc. 
![screenshot_301](https://cloud.githubusercontent.com/assets/7404959/20167342/8b4316f4-a723-11e6-99d4-aa0107477bbd.png)

But when i tried to put them on on "seemed" unused parts of fonts i got a scrambled result.
Is it still possible?

**Comment by ClockSelect** [comment]
Sure it's still possible, it's just that some former unused glyphs are now used (0xD4 and 0xD5 in your picture).
You can easily fix this since the + and - signs now exist in 0xFC and 0xFD so move your 0xD4 to 0xCD, 0xD4 to 0xCF, change the strings accordingly, and you should be fine.

**Comment by MoDuLah** [comment]
I'll give it another go and will let you know. :)
I used to use +/- with the locked lock below instead of Keys Locked message.
The rest are pretty obvious

**Comment by MoDuLah** [comment]
Done!!! Wish the transition to your next firmware to be so easy...
![2016 11 10 21 55 10](https://cloud.githubusercontent.com/assets/7404959/20193228/cb08df90-a795-11e6-929f-b5ce02c84308.png)
