### ISSUE TITLE
Strange values on display RX200S

### ISSUE THREAD

**Issue by Riadner** [ClockSelect/myevic#155]
I have setup 2 clicks for power on/off device. 4 clicks - none. To reproduce this bug I need:
Press 4 times quickly. This values goes normal after next 4 clicks.
https://goo.gl/photos/MWLyXqT8DZewXJjXA
https://goo.gl/photos/vWBR9T6aMtpS1m1D7
https://goo.gl/photos/Jwa9naCdaecm71kN6

**Comment by ClockSelect** [comment]
That's because you've set the DBG setting to ON in the expert menu (why did you do that?).
If DGB is ON, four clicks activates the debug display if nothing has been configured for the four clicks.
