### ISSUE TITLE
Need lower setting for ml/kJ please (lower than 200)

### ISSUE THREAD

**Issue by dabugen** [ClockSelect/myevic#156]
Hi,

even though I´ve set ml/kJ to 200 already, it still shows to much total used liquid (not talking about ml/Day). Yesterday I did reset the "ml" counter and have now just used ~5ml in reality, still the ml counter says 8ml. But I can´t set it lower than "200", which I´d need to make that work for my scenario. So can you please make it setable to lower than 200 (maybe to 100 or something).

Thank you:)

**Comment by ClockSelect** [comment]
Why not.

**Comment by dabugen** [comment]
Thanks :) Got mine accurate now with a value of 190 :) Now it matches what I´ve really vaped. Thank you!

P.S.: This is with:

Wismec Presa 100 TC
Geek Vape Griffin 25 Plus
Dual coil with 17 wraps 4mm 0.34 titanium grade 1 wick for each, at 0.64 ohm total for both combined
TCR M1 Mode with TCR value of 350
Starting power 100W
Max temperature 220°C

**Comment by afol2** [comment]
How do i Calculate the correct value for me ? @ClockSelect 

Oumier Whitebone with Single parallel coil of Kanthal 25gauge, and Clapton of 26 gauge and 36 gauge, 4 wraps @  0.232 Ohms.
Power mode at 45watts and a preheat of 55watts at 0.3 segs
Evic VTC mini

**Comment by ClockSelect** [comment]
You have to test.
Vape a known quantity of liquid, see the displayed result, and adjust the value proportionaly.

**Comment by enricorov** [comment]
Do you think is feasible to implement a 'calibration' feature?

Il ven 11 nov 2016, 15:31 ClockSelect notifications@github.com ha scritto:

**Comment by ClockSelect** [comment]
There's no way to do that.

**Comment by afol2** [comment]
ok, I'll do that

**Comment by enricorov** [comment]
@ClockSelect Why? Because of space constraints?

**Comment by SEEKNDESTROY** [comment]
@enricorov There are too many different variables... Number of coils, types of metals, coil designs, wattage or temperature setting, inhale time etc.
