### ISSUE TITLE
Suggestion: save/load the time setting

### ISSUE THREAD

**Issue by Derducken** [ClockSelect/myevic#157]
I'm not actually using the clock in my VTC Mini since it's a "first gen" version and I have to set it up from scratch each and every time I replace the battery (I use an external charger). I guess most people with the same, "plain" VTC Mini, charging their batteries in an external charger, are in the same position.

So, is there a way to save the settings to the equivalent of a txt file in some kind of "onboard storage" (like where the image is stored, as mentioned in another conversation we had here)? Yeah, that wouldn't make the need to tweak the time vanish, but you also wouldn't have to re-set *everything* from scratch - you'd just add 20 secs - 1 minute "to your previous settings" (as "loaded" by the mod when it turned on) and you'd be golden.

As always, "bottom priority feature" and just throwing ideas here :-)

**Comment by ClockSelect** [comment]
Time information is kept if you change the battery quickly enough - around 5~10 seconds. If you have the new battery by hand, it's plenty of time for a VTC Mini.
Another trick is to change the battery while connected to the USB, but it shouldn't be necessary.
