### ISSUE TITLE
request: port to RX200

### ISSUE THREAD

**Issue by dardares** [ClockSelect/myevic#159]
Does this firmware will be available for RX200? I would like to have it, but i've not the S rev...

**Comment by ClockSelect** [comment]
Not in a near future, I'm afraid.
But we never know, many peolple fork this project to make it evolve to their own purpose, so... I can't tell.
@e0x in #36 proposed something you could be interested in.

**Comment by zais1** [comment]
would be nice to have light custom smart mode with better ohm reading & hg2 batt profile tk

**Comment by ClockSelect** [comment]
I have a TC100W that'd love to power my firmware^^
It's just there; and I just tell her the same thing: let's hope someone will do it.
