### ISSUE TITLE
Suggestion: Clock face

### ISSUE THREAD

**Issue by Daveee10** [ClockSelect/myevic#162]
Hy! I think the screen saver analog clock looks better on VTwo mini. Can you make that for third clock face?

**Comment by enricorov** [comment]
Honestly, I prefer having numbers on the analog clock.

In fact, having such a clock is what brought me here.

Il sab 12 nov 2016, 15:57 Daveee10 notifications@github.com ha scritto:

**Comment by ClockSelect** [comment]
This thing take 1kB just by itself, that's why I've been reluctant to put it in.

**Comment by TBXin** [comment]
"Turned off" state after 5 clicks?

**Comment by ClockSelect** [comment]
I've an idea.
