### ISSUE TITLE
Bug in Screen Saver Pentagon 3D and More.

### ISSUE THREAD

**Issue by afol2** [ClockSelect/myevic#166]
Hi there, after the new commit  0cbf973  i just found that the screen saver pentagon, lags and then accelerate like FPS up and down. and in other hand some times with the experimental curve active, for a fraction of a second, it doesn't show wattage instead voltage.

Evic VTC-Mini

**Comment by ClockSelect** [comment]
Is that one or two issues?

**Comment by afol2** [comment]
Two issues

**Comment by ClockSelect** [comment]
So?

**Comment by ClockSelect** [comment]
If you have an issue opening issues, please open an issue.

![](https://www.dropbox.com/s/gzegd186jyzd7re/issue1.png?dl=1)

Sorry if I'm a bit rude, but what are we talking about in #166?
