### ISSUE TITLE
PPwr is off, but still works if set in Clicks menu

### ISSUE THREAD

**Issue by phantasm** [ClockSelect/myevic#169]
If you disable PPwr in Interface, but setup Clicks action to PPwr, it will still work.

Firmware: 0cbf97367095cda3d573cbad32b170acf34a585d
Box Model: RX2/3

**Comment by ClockSelect** [comment]
It's just to ways to toggle it on or off.

**Comment by phantasm** [comment]
Oh, didn't realize it from the beginning, sorry
