### ISSUE TITLE
[Idea]Preheat + Submenu + Reset + Battery

### ISSUE THREAD

**Issue by Daveee10** [ClockSelect/myevic#17]
1st idea:
IMO the preheat is a good thing but the power setting is not...
If I replace my tank to another with another resistance what needed another power very annoying thing how I need edit the preheat value...
I think better way how you make some preprogrammed value like this:
Soft : Power + 1W
Normal: Power + 3W
Hard: Power + 5W
Extra: Power + 7W
This values only ideas...

2nd idea:
I think a better way for editing the resistances a submenu seems like TCR Set or Preheat... 

3rd idea:
A menu for resetting puff counter, puff time and maybe setting the puff limit..

4th idea: 
On main screen before or after the battery meter a percentage battery indicator or percentage in battery image

I've got lot of idea but I think I need to make some, because I can't expect how You will make everything...

**Comment by npocmogu** [comment]
I would like the ability to adjust power to 1 watt (not 0.1) and reduce the number of taps of the fire button to turn on/off the device and navigate menu (3 clicks on/off, 2 click navigate menu - will be perfect).

**Comment by ClockSelect** [comment]
About the 3rd idea:

Since 3.03, puff/time counter are reset by a long click on + and - buttons while editing the third line with counter blinking. It's standard behavior.

**Comment by ClockSelect** [comment]
About the 4th idea:

I think battery meter is really enough; % won't provide more informations. It's fairly inaccurate anyway, the discharge curve depends on the battery brand and model. If I tell you 50% for 3.6 volts, it can really be anything from 25% to 75%. It would more or less be meaningless.

**Comment by npocmogu** [comment]
What are you talking about? Sorry, maybe I badly explained what I want? English is not my native language. I was talking about the power adjustment in vw mode. So when you press the + power was increased 1 watt, but not at 0.1 watt. And the second thing that I said to make the evic turn on/turn off after three clicks fire and 2 clicks to change mod (vw/tc/bypass).

**Comment by ClockSelect** [comment]
This is not standard behavior, and I try to stick with Joyetech's settings the users are used to.
The best we could do is at some point give the possibility to configure those in a menu, but not set it as the normal behavior of the firmware.

**Comment by ClockSelect** [comment]
Resistance editing has been moved in a submenu in lastest release; give it a try.

**Comment by npocmogu** [comment]
Ok, will wait.
When will approximately next update?

**Comment by Daveee10** [comment]
Ok, now looks better... I think this is a good way...
IMHO the TCR Set menu looks better if it looks like this menu, and the Power + Plus button method useless

**Comment by ClockSelect** [comment]
The TCR Screen is already written, so I keep it.
The Power+ button serves no other purposes, so I keep it too.

**Comment by ClockSelect** [comment]
@npocmogu: next update is already there.

**Comment by Daveee10** [comment]
I understand that but it not looks as same as other settings page.

**Comment by Daveee10** [comment]
You can replace the TCR set menu on Power + Plus button with Board temp what works with 10 or 20 click in original firmware, I don't remember...

**Comment by ClockSelect** [comment]
I really want my fw to be as close as possible in its behavior to the original.
If I modify things as you say, an issue will soon be opened telling that "TCR Set menu is no longer available".
I known that guenuine fw is not the most user-friendly over the place, but people are used to it. I do not want to scramble habits.
