### ISSUE TITLE
Bug on the 3D screen saver 

### ISSUE THREAD

**Issue by afol2** [ClockSelect/myevic#170]
Hi there, after the new commit 0cbf973 i just found that the screen saver pentagon, lags and then accelerate like FPS up and down.

Evic VTC-Mini

**Comment by ClockSelect** [comment]
Fixed.

**Comment by afol2** [comment]
Sorry for posting 2 issues in one..

**Comment by ClockSelect** [comment]
Never mind; at least, things go round again, now^^
