### ISSUE TITLE
"Zero all" command should also reset current resistance

### ISSUE THREAD

**Issue by phantasm** [ClockSelect/myevic#171]
If you want to reset current coil, you have to "Zero all" to clear it from the memory, and then reset the device itself, so it will recalibrate current coil on next start. I think it will be more convenient if "Zero all" command will also force the device to recalibrate current coil immediately. What do you think?

Box Model: RX2/3

**Comment by ClockSelect** [comment]
Why not.

**Comment by ClockSelect** [comment]
Reopen if neede.

**Comment by phantasm** [comment]
Seems that old coil resistance still stays.

**Comment by phantasm** [comment]
I cannot reopen this bug

**Comment by ClockSelect** [comment]
it's re-read, just not re-locked.

**Comment by phantasm** [comment]
Shouldn't it be also re-locked? The whole idea was to to avoid device reset, which is still required in current version.
