### ISSUE TITLE
Add please VV mode

### ISSUE THREAD

**Issue by valador** [ClockSelect/myevic#174]
Hello, maby you can add VV mode in firmware? Like a mechanical mod(bypass to hot in 9v). Or editing volt in bypass mode.

**Comment by Daveee10** [comment]
I think the VV mode is a good idea... I'm really liked my old iStick100 with that mode... 👍

**Comment by ClockSelect** [comment]
Done.
![](https://www.dropbox.com/s/65his5dff87nzx9/vv.png?dl=1)
Use (+) and (-) to change voltage, and press Fire to vape.

**Comment by ClockSelect** [comment]
I think you understood I won't do that.

**Comment by forkoz** [comment]
why?
