### ISSUE TITLE
Adjusted Wattage vary when vaping...

### ISSUE THREAD

**Issue by badummtss** [ClockSelect/myevic#180]
Hello ClockSelect, 
i have a Problem since yesterday, after i update on the newest version (161115 on wismec rx200s), my adjusted watt settings in powermode vary when i vape.
The ohm value is jumping from .249 ohms to .278 ohms and the Wattage value is jumping from 87.0 W to 88-89W. 
I don't have anything changed (in the new curve function).
I think it is a bug.
I don't have the same Problem on another RX200S with the same Atomizer, but with three other atomizers the same problem on this firmware.

**Comment by bluenazgul** [comment]
@ClockSelect here are the Videos from @badummtss Issue (the Videos are created by him)

The Video with the Issues
[Video with issue.zip](https://github.com/ClockSelect/myevic/files/597098/Video.with.issue.zip)

On older Firmware (befor the Power Curve Feature) without this issue
[Video without issue.zip](https://github.com/ClockSelect/myevic/files/597104/Video.without.issue.zip)

**Comment by acevalsl** [comment]
same error with etc two mini

**Comment by acevalsl** [comment]
video with jumping wattage
[IMG_2631.MOV.zip](https://github.com/ClockSelect/myevic/files/597130/IMG_2631.MOV.zip)

**Comment by fredsen1337** [comment]
Same problem with rx200s. Seems the curve funktion is not disabled properly. Before you added the feature there was no problem with the wattage.

**Comment by filippo90** [comment]
Here on RX 2/3 same issue of video!

**Comment by StepWi** [comment]
Just checked on Evic Basic with 2.6 Ohms at 10.2W: resistance and watt is oszillating a bit, roundabout 0.1 up to 0.2W, and less than 0.1 Ohms.

**Comment by afol2** [comment]
Same problem here with Cuboid and Evic VTC Mini, wasn't realizing that before i see this post.

**Comment by falconettt** [comment]
Don't bash me, boys, -)
but nothing bad happened to the curve:
![zxc](https://cloud.githubusercontent.com/assets/22370680/20392989/3af34f8e-aceb-11e6-9589-ee78dcb34523.jpg)

Yes, the power curve seems has some noise oscillations in first decimal.
But I like it! I'd be more glad even more controlled oscillations!
It's not a bug, it's feature (IMO)
/Vtwo mini/

**Comment by afol2** [comment]
> It's not a bug, it's feature 

Its like now is more accurate ? now you know the true power it is delivering ?

**Comment by StepWi** [comment]
At me it doesn`t look more accurate. Resitance is counting very fast from 2.58 to 2.61 and backwards. As we are talking at about 1 or 2% variation, it does not affect vape temperature - therefore I don't see this behaviour as feature, but as bug. But I have noticed this behaviour only because of readig this thread.

**Comment by ClockSelect** [comment]
It's just that know the actual wattage is displayed instead of the setting wattage - that we don't really care about. So there's some noise, inevitably.

**Comment by badummtss** [comment]
@StepWi you really mean that there is no worry about that? 
And @ClockSelect what i read out is, that this is more a feature than a bug?

**Comment by StepWi** [comment]
With the explanation from ClockSelect, that the actual wattage is displayed (feature), and the derivation of less than 2% I don't see any problem.
Remember, that the measurement of the resistance probably is worse than 2 %, you have internal wires, the 510 connector, wires and screws in your Atomizer, ..., so there is nothing to worry about in my opinion.

**Comment by ClockSelect** [comment]
I'd says that even if it was ±5% it shoudln't be too much of a concern.
Some boxes are good at reading numbers, others are bad, it depends on model and setup.
Anyway, showing setting numbers instead or real numbers does not solve the problem, it just hides it. But I guess it's less scary^^

**Comment by badummtss** [comment]
Thank you Guys for your explaination about this. 
Ok then for me i have a disco lighter instead of a Mod Box ^^.

Great Job but before i eat fish i would drop the fishbones away - you know what i mean ;)

Thank you Very much for that great piece of software @ClockSelect .
