### ISSUE TITLE
RX2/3 2-3 cell box freezed

### ISSUE THREAD

**Issue by neodjoo** [ClockSelect/myevic#181]
Hey all, first of all, thank u all for the contribution, i ve set the myevic firmware in a RX2/3 box, it work fine in 2 cells than i used the 3 cell after that i went to the 2 cells the box wont work, it seems like the box can't read the 2 batteries, can't vape nothing, any issues?thanks a lot
![20161117_172430](https://cloud.githubusercontent.com/assets/23527974/20398166/94e774b0-acec-11e6-8809-5f225e8aa2d6.jpg)
![20161117_172504](https://cloud.githubusercontent.com/assets/23527974/20398229/e25e7310-acec-11e6-909b-f7af15ae2da5.jpg)
First pic: with 2 cells
Second pic: with 3 cells

**Comment by ClockSelect** [comment]
A similar issue has been discussed here: #163
I don't know if ti will help.

**Comment by Filo301** [comment]
I had this same issue. Top balancer cable was broken.

**Comment by neodjoo** [comment]
ok thanks for the contribution, seems like it's the same case!
