### ISSUE TITLE
Games On Evic Vtc Mini

### ISSUE THREAD

**Issue by anderlobo** [ClockSelect/myevic#186]
https://www.youtube.com/watch?v=1wyj3uMJNE8 Google browser game, no internet connection.
https://www.youtube.com/watch?v=8Q2mwnvBaGQ Snake on e-cigarette (eVic-VTC Mini).

It would be possible to do one of these, I imagine it should weigh a few kb.
thanks...

**Comment by drminol** [comment]
Do you have a smartphone? Who the hell are playing games on the ecig?! It hasn't any sense...

**Comment by marvinerzz** [comment]
I have a smartphone, but it'd be nice to have a few games on my vape every now and then for lulz

**Comment by LockManipulator** [comment]
I agree, I love having flappy bird and would love more games too.

**Comment by ClockSelect** [comment]
I'm afraid I won't use the last few available kB for that.

**Comment by Daveee10** [comment]
@ClockSelect: The data storage area can't usable for store the settings? Maybe something movable from dataflash.
