### ISSUE TITLE
New Cuboid 200 with a new Firmware (enhancement)

### ISSUE THREAD

**Issue by afol2** [ClockSelect/myevic#192]
Hey there, 
A new Cuboid with 200 watts with 3 batteries has just been release, with it a new firmware (6.04),
It will be cool if the layout of the firmware could be changed, it has more lines that could be personalized (like the 3th line in your software). I think it would be a aesthetics upgrade to your firmware. I'm not a programmer so i don't really know how difficult it could be. Let me know what you think.

![image](https://cloud.githubusercontent.com/assets/22644918/20526817/327306d8-b09c-11e6-92ea-4a33e06f9853.png)

here is what it looks like.

**Comment by ClockSelect** [comment]
The experts of line customization are @TBXin and @maelstrom2001; I'm sure they will do it within days.
If they have some compatibility issue, we'll work together; but that's not your point.

**Comment by afol2** [comment]
that should be great.! @ClockSelect

**Comment by drminol** [comment]
Nice! ❤️

**Comment by ClockSelect** [comment]
Things will be done once I'll revamped screen management.

For now, we're compatible with Cuboid 200, that's not so bad :)
