### ISSUE TITLE
Stealth-mode + inverted doesn't turn off screen

### ISSUE THREAD

**Issue by skipperbent** [ClockSelect/myevic#195]
**Issue:**
At the moment having inverted screen activated doesn't turn off the screen when Stealth mode is activated. Instead it just shows a blank white screen with the background light enabled.

Really appreciate what you've done with the firmware! Insanely great work!

**Model:**
eVic VTC Mini w/ Cubis 0.6 ohm coil.

**Comment by SEEKNDESTROY** [comment]
[ ClockSelect commented](https://github.com/ClockSelect/myevic/issues/36#issuecomment-259326962) Nov 8, 2016

>That's what is does. It fades to black, but since it's inverted, it shows white^^
Only when it switches off (in sleep mode) will it go to black. That's after 3 minutes of inactivity without screen saver or at the end of screen saver duration (or when you switch the box off).
Max power consumption of pixels is 100µA/line, that's 12.8mA for a full white screen at 100% contrast (half of that at 50% contrast and so on).
So yes it's not neglictible.
