### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by MoDuLah** [ClockSelect/myevic#196]
I really would like to see the read me on .pdf would be easier to share and see even without internet connection.

**Comment by ajape1** [comment]
@MoDuLah Install a free PDF printer on your computer and then print the main webpage, like the attached PDF.
[myevic.pdf](https://github.com/ClockSelect/myevic/files/615165/myevic.pdf)

**Comment by ClockSelect** [comment]
@ajape1 : smart.
