### ISSUE TITLE
Manually change puff counter? [Question]

### ISSUE THREAD

**Issue by dexty32** [ClockSelect/myevic#197]
Is there a way to manually change your puff counter? I like to keep track how many puffs i have total, but after i did my first update, it reset it, id like to manually add it back up now, if thats possible?

evic VTC mini.

**Comment by kcypher** [comment]
Hello, I can do this for you, if you want!

**Comment by dexty32** [comment]
That would be great! how would it work, will you give me a download link or something? If you can, set it at 26k puffs.

edit: closed by accident for a second, my bad.

**Comment by kcypher** [comment]
Wich FW do you use? The newest myevic from this repo? I would make a new menu to change manually the puffcounter. I would send it to your email, if this would be no problem for you.

**Comment by dexty32** [comment]
Yeah, the newest one, and e-mail would be great! Thanks for helping by the way for not that important or an issue.

**Comment by kcypher** [comment]
I have still one question: Wich Box do you have? Maybe this could be good to know, haha!

**Comment by dexty32** [comment]
evic vtc Mini :D

**Comment by kcypher** [comment]
Ok, give me some time. I tell you when i'm done. Maybe 1h or so. ;-)

**Comment by kcypher** [comment]
Ok, finished. Whats your mail?

**Comment by dexty32** [comment]
Oops, I was already sleeping.

Thanks for the help :)

**Comment by kcypher** [comment]
Ok, sent it to you. In the Vapingmenu there is now a new Submenu called PuffCount. Here you can manually set the PuffCounter. 
Pls let me know if everything works just fine, or not.

**Comment by dexty32** [comment]
Thank you! I'll try it later tonight and I'll let you know if it works.

**Comment by kcypher** [comment]
Hello, do you tested it?

**Comment by ClockSelect** [comment]
That's exactly the way I like seeing people interacting on this firmware. Thanks, guys.

**Comment by dexty32** [comment]
Sorry, took a while to reply. But it works great kcypher, thank you so much! Takes a little while for the scrolling but wont be doing this again for a while anyway.

Have a great day!

**Comment by dexty32** [comment]
Hey, i have one last question, i was was using one of the older myevic firmwares, now i installed the one kcypher gave me, i assume its newest one, the wattage now jumps down and up realtime, aswell as the ohms, my ni80 coils are going from .218 to .240 when firing, is that normal? Thanks.

**Comment by kcypher** [comment]
I took the newest one, yes. I'm not so familiar with temp-vaping. The only thing i know is that you have to lock the coil resistance. But i'm sure that you've done this already! However, it has nothing to do with the PuffCounter, don't worry! :-D

**Comment by DanielDrew93** [comment]
I would also like to change my puff counter too, unless its already in the firmware now?

I'm currently on 30k puffs on the default wismec software
