### ISSUE TITLE
Hardware version is cleared

### ISSUE THREAD

**Issue by TBXin** [ClockSelect/myevic#2]
After uploading your firmware hardware version in the dataflash erased with following bytes FF FF FF FF.
This can "brick" the device after rolling back to the stock firmware, since they are using this data to initialize correct LCD - 1306 or 1327.

Also, reset dataflash function does not restore correct HW Ver. 
The only way is to manually edit dataflash and then upload it.

**Comment by ClockSelect** [comment]
Fixed.

The DataFlash CRC was not correctly computed, since the CRC_MODULE clock was not enabled. So the OFW considered all DF pages as invalid.

**Comment by ClockSelect** [comment]
(Anyway, that's strange: uneless everything has been cleared in the dataflash, the hardware version should always be recovered, even if CRC is bad).

**Comment by ClockSelect** [comment]
Thanks for your reports!

**Comment by TBXin** [comment]
Good job! Now it's work properly :+1:

**Comment by slavyk** [comment]
Great work but is possible to restore original HW version?! My eVic was HW1.00... and now is -0.01!

**Comment by TBXin** [comment]
@slavyk i know one way:
1. Read dataflash from your device to PC via NFirmwareEditor or python-evic;
2. Manually edit file via HEX-editor of your choice;
3. Write dataflash to your device;

Explaining 2nd step: at the beginning of the dataflash file look for FF FF FF FF, and replace them with 64 00 00 00.

**Comment by slavyk** [comment]
Thanks, TBXin! Now it's 1.00!

**Comment by ClockSelect** [comment]
Sorry for the inconvenience -- loosing the Hardware version is the worst thing that can happen on that box. This should not happen any more (hopefully).
@TXBin: thanks for the recovery method.
Question is: was really the HW version 1.0 before? Some version differ only by the atomizer shunt resistance value, and reseting to 1.0 to, say, a 1.01, will set the shunt resistance value off by .1 ohm, with no other visible effect. All seems to work perfectly. But it will shift all power/temp values by an unpredictable amount.
I guess it's really important to know what is the HW version of the box before messing with the firmware in any ways.

**Comment by slavyk** [comment]
Yes, it was for sure HW 1.0 before.

**Comment by slavyk** [comment]
I try the latest version... 
![clipboard01](https://cloud.githubusercontent.com/assets/20903668/17726597/c6fdf8e4-645c-11e6-9a13-f8688aed8dca.jpg)
After flashing: 
![clipboard02](https://cloud.githubusercontent.com/assets/20903668/17726611/da48f7e6-645c-11e6-9edd-3edead849ea8.jpg)

**Comment by TBXin** [comment]
> I try the latest version... 

@slavyk can you try to upload firmware in the safe mode?
1. Remove battery
2. Press and hold plus button
3. Connect to the USB
4. Release plus button
5. Device will be recognized with 0.00 firmware version

Then upload firmware from file.

**Comment by slavyk** [comment]
Hi! It was not appropriate to use safe-mode. I uploaded the previous version without any problem. All works fine now.

**Comment by ClockSelect** [comment]
What do you mean by "previous version"?
Is there anything preventing you from using the latest version of the software?

**Comment by slavyk** [comment]
Sorry for my english... :-1: 
I mean this: myevic.bin from 13.08, 68.7k 
I try to upload latest version with NFE but what happened you can see in images. 
So, i use the safe mod, upload official version 3.03 with official firmware updater. After that, using the same firmware updater i upload myevic_encrypted.bin. NFE it's not suported anymore. Now everything works well, i can feel the difference of 0,01 Ohm! As a suggestion, temperature control can be with step 1 degree Celsius? I tried it with version 3.02 patch and even feel the difference, although I would not have believed it!
Thank you for your avesome work! :+1:

**Comment by TBXin** [comment]
> NFE it's not suported anymore

@slavyk  Что ты имеешь в виду? О_о

**Comment by slavyk** [comment]
I failed to write with NFE-Firmware Updater the new versions of ClockSelect.

**Comment by TBXin** [comment]
@slavyk it's very strange. Just now successfully uploaded myevic.bin and myevic_enc.bin (latest version from repository).

**Comment by slavyk** [comment]
Yes you are right! It is very strange! I tried again, right now. It was uploaded without any problems. In the morning I tried several times, but it appeared to me the same error message as in the pictures above.

**Comment by TBXin** [comment]
@slavyk sometimes USB interfaces stucks, and this is OS issue i guess. After a few minutes all starts working fine.
