### ISSUE TITLE
Hardware upgrading possible?

### ISSUE THREAD

**Issue by kcypher** [ClockSelect/myevic#200]
Hello @all,
does anybody know if there are some spare IO's on the VTC mini or VTwo Mini? Could it be possible to add for example a little piezo buzzer to add some alarm functions (especially on boxes with rtc chip), or an ESP8266 wifi module? That would be amazing!
http://www.esp8266.com/viewtopic.php?f=13&t=475

**Comment by ClockSelect** [comment]
There is some spare IOs but not many space on borard or inside the box.
The best option is to use a spare serial port (SPI, I2C or UART) to communicate with whatever you want.
