### ISSUE TITLE
Rx 2.3   USB 

### ISSUE THREAD

**Issue by Teerapong2534** [ClockSelect/myevic#201]
**Box Model:**

**Coil setup:**

**Comment by Teerapong2534** [comment]
![15301116_232710030494139_1266804918_n](https://cloud.githubusercontent.com/assets/23415935/20826340/c3417e62-b89c-11e6-8fc1-2925b3c57a83.jpg)
![15327786_232710017160807_1619832271_n](https://cloud.githubusercontent.com/assets/23415935/20826341/c346d16e-b89c-11e6-9496-1d4d05f8a783.jpg)

**Comment by TBXin** [comment]
![](http://i.imgur.com/B3No8tI.png)

**Comment by Teerapong2534** [comment]
![15310500_232813627150446_995201292_n](https://cloud.githubusercontent.com/assets/23415935/20834346/666881ec-b8c7-11e6-8258-80beb60141e9.jpg)

**Comment by ClockSelect** [comment]
Is there still an issue?
