### ISSUE TITLE
Display mAh

### ISSUE THREAD

**Issue by arafey** [ClockSelect/myevic#202]
It would be useful to view the amp-hours used since last charge in order to monitor battery usage or to diagnose a failing/old battery with a low charge capacity. 

It should be theoretically possible to have this since we already can see the "on" time in the puff counter as well as the instantaneous battery output current.

**Comment by arafey** [comment]
Also, I'm assuming if this option is implemented, it could be located on the third line (where the puff counter, mL/day, etc. is), or as an alternative to battery percentage or voltage. The latter option would require a preset and/or a user-adjustable "battery capacity" value (probably between 1000-4000 mAh is a good range) in order to decrement the battery bar at an appropriate rate.

**Comment by easyyu** [comment]
This option would be really nice...

**Comment by MicroSur** [comment]
There are no sensor to get real current from battery itself.

**Comment by arafey** [comment]
Wouldn't Ohm's Law be sufficient? We also don't have sensors to measure mL of liquid but that option still exists.

**Comment by MicroSur** [comment]
If you store efficiency of all cirquit boards for each mods and for different powers...

**Comment by arafey** [comment]
Without that efficiency information, you would probably have up to 15% error in the reading (assuming most boards are at least 85% efficient), but that's still valuable. If you include a user-adjustable offset (like mL/kJ option for the mL display) then users can calibrate it to remove that error. My mL reading had 50% error originally, yet that option still exists.

**Comment by ClockSelect** [comment]
That's doable, but since your charger gives you the mAh when recharging the batteries, what's the point to have it on your box?
Regarding built-in batteries, problem lies in box efficiency that's not really measurable.

**Comment by arafey** [comment]
You're right, most chargers do give mAh and I didn't consider internal batteries. Some people also use the USB port to charge. 

I still think it's worth eventually adding but it should be low priority.

**Comment by ClockSelect** [comment]
Trick: if you set your mL/kJ ratio to 100, the liquid displayed will in fact be total energy dissipated in tenth of KiloJoules (Joules x 10e-4). Multiply by 10000/3.6 and you have the mAhV (milliAmp-hour-Volts) value. Divide by your mean voltage (say, 3.6 for a generic battery) and you have a rough value of your mAh.
You may divide by 0.9 to take chipset efficiency into account (90% seems a not-too-bad value).
(TL;DR: multiply a ratio 100 liquid by 857)
