### ISSUE TITLE
Disable Inverted Display on some Screens

### ISSUE THREAD

**Issue by sandboxgangster** [ClockSelect/myevic#212]
**EVIC VTC Dual**

Hello, please Disable the Inverted screen on Blank screens, Load Animation, Screensaver off Mode, it’s  Display Always on this ist not good for the OLED.

mfg SB

**Comment by drminol** [comment]
Why? It's an option. Who told you that you must use it? Is enyone who? If you crash your screen, it's your problem. Cheers. :)

**Comment by drminol** [comment]
And one more thing. It's not bad for the OLED screen, but only for the battery.

**Comment by sandboxgangster** [comment]
Why so bitchy?
It is a suggestion to make a meaningful improvement to prevent aging.

Quote from Wikipedia (Translate from German Wikipedia):

Https://de.wikipedia.org/wiki/Organische_Leuchtdiode#Nachteile

The greatest technical problem is the comparatively short lifetime of some components made of organic materials. For (O) LEDs, the lifetime is the average operating time after which the luminance has decreased to half. For white light sources and monitors, the blue component is limited for the total useful life. In 2011, 5000 hours (at 1000 cd / m²) [16] and 12,000 hours (at 100 cd / m²) were reported for white light sources [17]. ...

**Comment by drminol** [comment]
Because it's an option. No one tells you to use this option. But certainly are people who would like to use it, even at the cost of the screen life. We shouldn't limit other people. If you don't want to damage the screen or battery simply doesn't enable this option.

**Comment by sandboxgangster** [comment]
Is ok, is nicht mein Projekt war nur ne idee wenn man den Screen Saver aus hat, ist nen total weißes Display total sinlos dafür schaltet man den doch aus das gerade nix angezeigt wird.

Macht das wie ihr denkt, war ja nur ne idee

**Comment by sandboxgangster** [comment]
Is ok, is not my project was only ne ideae if one has the screensaver, is nen total white display totally sinlos for it switches the nevertheless from the straight nix is displayed.

Does that as you think, was only ne idea

you can close this than

**Comment by sandboxgangster** [comment]
Is ok, is not my project was only ne ide when you have the screensaver off, is a white display totally senseless for it turns off the nevertheless from the straight nothing is displayed.

Does that as you think, was only ne idea
