### ISSUE TITLE
Cuboid 200 compatibilty

### ISSUE THREAD

**Issue by simonec85** [ClockSelect/myevic#216]
Hi, can you add compatibility whit the new Cuboid200 ?
My box whitout your firmware is no the same!
Thanks in advance

**Comment by ClockSelect** [comment]
It will be done.
@maelstrom2001: how far have you advanced on this project?

**Comment by TBXin** [comment]
@ClockSelect we currently not interested in this devices, because its so rare.

**Comment by ClockSelect** [comment]
@simonec85 Could you [test this version](https://www.dropbox.com/s/6878hw1w0ufei1t/myevic.bin?dl=1) on a Cuboid 200?

(Or anyone here with a Cuboid 200)

**Comment by simonec85** [comment]
Hi, i'm now testing this releas and it work properly, like on my Cuboid 150W, thank you

**Comment by ClockSelect** [comment]
@simonec85 Thanks to you :)
Released.
