### ISSUE TITLE
shutdown

### ISSUE THREAD

**Issue by npocmogu** [ClockSelect/myevic#22]
When I increase power, evic vtwo mini suddenly shutdown and don't turn on no more. Via USB charge nothing shown on display. What's happening? Evic is dead.. Don't have any pc at this moment (1day) to check connect with pc.

**Comment by Daveee10** [comment]
Open the firmware update tool,vremove the battery press and hold the plus button and connect to pc... Now flash the original firmware. Remove USB key put the battery in and be happy :)

**Comment by npocmogu** [comment]
Thx, will try tomorrow

**Comment by ClockSelect** [comment]
When battery voltage comes beyond 3.0V, the box will refuse to wake up.

**Comment by npocmogu** [comment]
Battery voltage was approximately 3.6v

**Comment by npocmogu** [comment]
It's okay, Evic alive
