### ISSUE TITLE
Not really an issue, where to find changelog?

### ISSUE THREAD

**Issue by quentin6633** [ClockSelect/myevic#222]
I searched but didn't found it, is there a changelog?
I saw you made a modification 2 hours ago, i'm using previous build on my RX2/3, working perfectly!! So i want to know if it s necessary to do this update :-)
Thanks all for the hard work it's really a good firmware, so many possibilities compared to the stock one...

**Comment by bluenazgul** [comment]
It is easy, just check the commits - the Last change was "NFE Compatiblity"

Am 22.12.2016 18:02 schrieb "quentin6633" <notifications@github.com>:

**Comment by quentin6633** [comment]
Thanks mate, didn't found it. Even on mobile version you can access to it?

**Comment by SEEKNDESTROY** [comment]
Try this [Commits](https://github.com/ClockSelect/myevic/commits/master)

**Comment by SEEKNDESTROY** [comment]
I hope this helps...
![untitled](https://cloud.githubusercontent.com/assets/22176387/21434410/58bd630c-c842-11e6-99d2-57f89aa815a6.png)

**Comment by quentin6633** [comment]
Yeah mate it helps! With your link i acces to it directly, and found also where i can access to it.
On the main page, need to click on "view code" and after that here it is :-)
Thanks dudes for your help!
I'm not an expert on Github, just subscribed today :-)
I can close this "issue" now ;-)

**Comment by SEEKNDESTROY** [comment]
No problem... we were all new to this at one point.
