### ISSUE TITLE
Preheat bug when turned off

### ISSUE THREAD

**Issue by quentin6633** [ClockSelect/myevic#225]
**Box Model: Reuleaux RX2/3 with vtc6 batteries

**Coil setup:Aromamizer Supreme with dual 3mm ID clapton coils

I have set the preheat at 70w, 0.5sec time and 0.20 delay.
When I vape on it, and just after I turn it off, when I turn it back on the "P" indicator is still blinking, after a long power off wait, clearly more than the delay time, i tested even with a 5 minutes powering off time.

I'm on the previous build, the one just before the NFE comp update.

The clock is set, the date also.
And i changed no setting in the expert menu

**Comment by ClockSelect** [comment]
Yes it restarts the preheat delay timer where it left if at power off.

**Comment by ClockSelect** [comment]
Should be fixed

**Comment by quentin6633** [comment]
Nice! Thanks mate! Will try as soon as my RX2/3 is replaced, the chipset is fried, no display...

**Comment by ClockSelect** [comment]
Real hardware issue?

**Comment by quentin6633** [comment]
For sure tried all i can :-) you can have a look at the problem on this video https://youtu.be/f7kxq3Vm0fg

**Comment by ClockSelect** [comment]
Weird!

**Comment by quentin6633** [comment]
Yeah it stopped working just after firing it.
When i wake and put the batteries in, it works for like 5 minutes max, but it is very weak, no brightness, and after that only info i can display is the lock/unlock and if i don't wait for it to disapear and click on fire, the display do a kind of flash and go back to black.
Tried so many things... 4 days after receiving it's a bit frustrating....
