### ISSUE TITLE
[REQUEST] Pin descriptions for various devices

### ISSUE THREAD

**Issue by kablek** [ClockSelect/myevic#228]
Hi!

I started building my own source since I am having some problems with cuboid and arcticfox people just marked my issue as wontfix. I seem to kind of understand most stuff but it would be really helpful to know which GPIO does what. Is data like that available anywhere?

**Comment by ClockSelect** [comment]
There is a constants.txt file among with the sources which describes the IOs for the VTC Mini; there are some variations form box to box but they're not listed. It's a good starting point anyway. Mix that with the megpio.c and tha main.c sources and you should have all the information you need.
