### ISSUE TITLE
[Idea]Charge screen saver

### ISSUE THREAD

**Issue by Daveee10** [ClockSelect/myevic#23]
Screen saver on charge screen.. The configured screen saver can displayed on the charge screen....

**Comment by ClockSelect** [comment]
They're is no such thing as a charge screen, atm. Device is up and running in a fraction of a second.
When you take your device in hand, the only thing you usually want is to press button and get nicotine.
I don't really see the point of this feature.

**Comment by ClockSelect** [comment]
Or maybe I don't understand what you call "Charge" screen?

**Comment by Daveee10** [comment]
When you connect the usb charger. Now we can see the battery voltage board temp and battery indicator. Top of this infos we can use the screen savers.

**Comment by ClockSelect** [comment]
Oh, I see.
Why not. I'l give a look.

**Comment by ClockSelect** [comment]
done.
