### ISSUE TITLE
Compatibility for RX Mini, please!

### ISSUE THREAD

**Issue by krudas** [ClockSelect/myevic#230]
**Box Model:** Wismec RX Mini

**Coil setup:**

**Comment by ClockSelect** [comment]
Should work, but could not test.
Returns welcome :)

**Comment by krudas** [comment]
Sorry m8, but doesn't seem to work, still error

**Comment by ClockSelect** [comment]
What kind of error?

**Comment by ClockSelect** [comment]
Try this one... never knows.
Since the box ID appears several times in the firmware file, the uploader may be mistaken.
This could be the issue.

**Comment by krudas** [comment]
![wismec](https://cloud.githubusercontent.com/assets/19902621/21538926/252e28b8-cda2-11e6-9e16-3453a6173af2.jpg)
Still "The firmware file is error"

**Comment by krudas** [comment]
Ok, now I downloaded the master file and extracted the .bin from that. Now it works so far, but the clock doesn't accept any setups. I suggest the RX Mini doesn't have any RTC onboard ...

**Comment by ClockSelect** [comment]
Yes, RXmini has no built-in RTC so using RTC features may have random results.
