### ISSUE TITLE
VTC Mini no longer recognized by update tool after #230 update

### ISSUE THREAD

**Issue by deadpan421** [ClockSelect/myevic#232]
I flashed the update posted a few hours ago, #230, on my eVic VTC Mini using the standard Joyetech update tool for Windows.  I connected it again a few minutes later and noticed the update tool no longer recognized the device.  I tried turning off the device, removing the battery, removing the tank, using a different usb cable and port etc, but couldn't get the tool to acknowledge the device.  I ended up opening up NFirmwareEditor v.6.3.0 and used that to try to flash the previous update from a week ago, but that tool didn't recognize the device either.  I began playing with the different options within NFirmwareEditor (this is the first time I've tried using it), and clicked 'advanced' and then 'change boot mode' - and finally the device was recognized!  I tried opening up the Joyetech update tool and  again, the device was recognized.  I flashed the update from a week ago successfully and everything is back to normal.  Just a heads up to any users who find themselves in a similar situation and are uncertain of how to resolve the issue.

Thank you for your amazing work on this project!

**Comment by Gremdude** [comment]
Same problem here with the Cuboid. No longer recognized by the tool. No Mac version of NFirmwareEditor so I guess I am out of luck?

**Comment by deadpan421** [comment]
Hey @Gremdude I don't have a Mac, but the gentleman on this forum (http://vapingunderground.com/threads/custom-firmware-editor-for-the-wismec-reuleaux-rx200-joytech-evic-vtc-mini-cuboid-200x.213320/) indicated he was able to use Wine on his Mac to run the NFirmwareEditor.exe file.  Perhaps that would work for you as well?

**Comment by ClockSelect** [comment]
Bug spotted, thank you.

On any platform, you may reboot your box to the LDROM to fix the issue; to do so, you just have to hold the right button while the box resets. There are many resources down there that explain the procedure.

**Comment by deadpan421** [comment]
Update flashes and works perfectly, many thanks! Happy New Year :)

**Comment by Gremdude** [comment]
No problem. I got it working again. Hopefully this version gets pulled before it frustrates too many other users!
