### ISSUE TITLE
Fire button still fires in Key Lock

### ISSUE THREAD

**Issue by membranepotential** [ClockSelect/myevic#233]
Box: VTwo mini

After setting keylock by holding + and -, the fire button still works. + and - lock as expected.

Cheers

**Comment by Riadner** [comment]
Only + and - is locking. Fire must work after lock. So its work as expected.

**Comment by membranepotential** [comment]
Oh ok I thought the key lock is a safety feature to prevent accidental firing? In what situation would I only want to lock + and -?

Cheers

**Comment by membranepotential** [comment]
I see in the original firmware it works the same. My bad. I always thought the key lock would lock everything.
