### ISSUE TITLE
'Please confirm hardware version'

### ISSUE THREAD

**Issue by Shure123** [ClockSelect/myevic#234]
----------
**EDIT 2**: **I did manage to update using NFirmwareEditor 6.3 without issues**, however the Wismec Updater does not work. 
------------

I cannot update my new RX2/3 with the myevic.bin firmware. I keep getting this **'please confirm the hardware version!!'** message:  http://imgur.com/3TUfYNO

_Hardware version is 1.02_. 

- I can succesfully upgrade and downgrade between 4.03 and 4.13, so the updater and usb cable work.

- I can also upgrade my eGrip2 with the same bin, so the file is not corrupt.

- I cannot find any information about this 'please confirm the hardware version' message, nor do I know how to confirm it. It only gives an 'ok' button which just returns me to the begin screen. 

- I tried with the device on & off, by connecting before & after opening the updater, and with & without batteries installed. 

**Box Model:** RX2/3, hw version: 1.02, fw version: 4.13 (+ 4.03)

![screenshot](https://cloud.githubusercontent.com/assets/24841548/21565248/ba0c0452-ce95-11e6-8f3c-54bf69e02ef6.jpg)

Thank you for reading.

**EDIT 1** 

1. Here I found what appears to be a fix from Clockselect for this issue, but the RX2/3 isn't included yet in this fix, could that have something to do with it?
https://github.com/ClockSelect/myevic/commit/ebac1b596ddc38f957d766d6878939a2a9eca667
From: https://github.com/ClockSelect/myevic/issues/80

2. My updater does read the firmware 1.02, so I don't think it is lost and should be re-added.

**Comment by ClockSelect** [comment]
myevic is not compatible with RX2/3 hardware version 1.02 (yet) since this hardware did not exist at the time RX2/3 compatibility has been developed.
So I don't recommend you flash your box with myevic untill I check for RX2/3 v1.02 compatibility.

**Comment by ClockSelect** [comment]
There something strange, there: if I take a look at official Wismec firmwares, they're supposed to handle only up to 1.01 hardwares. So you shouldn't even be able to downgrade to 4.13.
When did you got your box?

**Comment by ClockSelect** [comment]
I had a look and Wismec silently changed their firmware files to include hardware 1.02 without changing firmware versions and dates. Neat.

**Comment by Shure123** [comment]
Thanks for your fast answer. I am really liking myevic (big thanks!). So far everything works fine, I'll test it some more and can report any issues.

If you like, I can remove the workaround from my post until you deem it safe though.

**Comment by ClockSelect** [comment]
It seems that there's no significant changes in firmware related to hardware version.
At least nothing dangerous.

**Comment by easyyu** [comment]
I have same error message..
After I try to install firmware my VTC VTwo is dead.
Only with firmware before this I can flash it and make it work again.
What can I do to make work with latest firmware?
Is it a bug?
![bug](https://cloud.githubusercontent.com/assets/24247397/21575642/c1e43cde-cf13-11e6-923a-6889eaa3ccf2.jpg)

**Comment by Shure123** [comment]
@easyyu Try to press all 3 buttons after flashing when it is 'dead'. For me that brought it back to life.

@ClockSelect I ran into the first issue. It's minor, but considering your name, it might bother you more than others ... Clock: SetTime and SetDate don't work. I can 'change' the time and date, but it doesn't change anything after I exit the menu. The date is still 2084. The time can be changed with ClckAdjust but that's tiresome.

**Comment by SEEKNDESTROY** [comment]
@Shure123 long press the power button to save the date.

**Comment by quentin6633** [comment]
Mine says also hardware version 1.02, but was able to install the firmware without problem.
Can my problem of fried chipset or chipset come from here? After this problem, tried to install all the official firmwares available so it's a not a soft problem for sure.
I'm receiving the new one tomorrow will wait before installing :-)

**Comment by JOOKERO** [comment]
how can i know the version of my RX2/3  ? i install myevic and i love it , but the upgrader still show : version 1.00

**Comment by Shure123** [comment]
@JOOKERO Then 1.00 is the hardware version of your RX2/3. That won't ever change. 
To check the software version, click the fire button 20 times.

**Comment by JOOKERO** [comment]
it shows : (myevec , build 161230 , version 3.30) , with NFirmwareditor i have 1.02 hardware version , would you tell me the diffrence between 1.00 and 1.02 version ??

**Comment by easyyu** [comment]
I want to ask development, why I can not use from aprox 22.Dec.2016 release any more this firmware on my Evic VTwo mini. 
I always get error: Please confirm the hw version.
My Vtwo have hw verision v1.01, readed by FWupdater v1.2
Thx

**Comment by easyyu** [comment]
Any news?

**Comment by ClockSelect** [comment]
@easyyu VTwo Mini 1.01 is a new hardware version.
I have to check for its compatibility.

**Comment by ClockSelect** [comment]
@JOOKERO : I've seen no firmware-related difference between the two; maybe they just changed some random component on the PCB.

**Comment by easyyu** [comment]
> >  ClockSelect commented 7 hours ago
> 
> @easyyu VTwo Mini 1.01 is a new hardware version.
> I have to check for its compatibility.
> 
Thx for answer.
But then why I can not use anymore fw you made?

**Comment by ClockSelect** [comment]
It's because HW version was badly checked before.
You should be able to use it again, now :)

**Comment by easyyu** [comment]
> @ClockSelect
> 
> It's because HW version was badly checked before.
> You should be able to use it again, now :)

Thx mate..now I can again use your FW!
