### ISSUE TITLE
RX300 Compatibility

### ISSUE THREAD

**Issue by docdeath** [ClockSelect/myevic#235]
**Box Model:**

**Coil setup:**

**Comment by ClockSelect** [comment]
I didn't look at the RX300 yet; since it's an unusual multi-cell box, it may (certainly will) take some time to adapt.

**Comment by ClockSelect** [comment]
For those of you ready to take some risks, I made [an experimental RX300 version of the firmware](https://www.dropbox.com/s/6878hw1w0ufei1t/myevic.bin?dl=1).
Charging via USB is not yet enabled; it's the most dangerous feature and is not ready yet.

Since I have no RX300 by hand I cannot test by myself so I must rely on the good wills down there.

**Comment by docdeath** [comment]
it loads fine and works as in you can use menus but it comes up with flashing battery icon  at bottom and when you hit fire button it say check  battery's i changed to fully charged set dose same .menu seams to all work  apart from  it will not fire

**Comment by ClockSelect** [comment]
What do the battery voltages read for each of the four cells?
You can see them in Expert->BVO menu.

**Comment by ClockSelect** [comment]
Ok I found a bug in battery reading.
You can [retry](https://www.dropbox.com/s/6878hw1w0ufei1t/myevic.bin?dl=1).

**Comment by ClockSelect** [comment]
Thank you for your help, BTW^^

**Comment by docdeath** [comment]
that has solved  battery problem now as you hit fire it says device to hot  flashing up

**Comment by docdeath** [comment]
no problem with helping as love your firmware

**Comment by docdeath** [comment]
i have been though all the menus now and as far as i can tell it all works  .just the device to hot when you hit fire button

**Comment by ClockSelect** [comment]
What's the board temp?

**Comment by docdeath** [comment]
85 c then i hit fire button to see broad  temp 10  times and its now reset self to 30 c do you want me to  reload firmware again see if it dose this again ?  i just changed battery's over and its  saying device to hot with mod temp at 85c  and this time it will not work or reset if i hit fire button 10 times like be for so what i have done is reloaded firmware and hit fire button loads and its reset temp and works. hit fire button 10 times and mod temp is 36 and working fine take battery's  out and  its reset temp to 85 and have to do same again reinstall firmware and hit fire button loads  .now i have removed battery's and done the above and it works now its saying weak battery's as it fires up it still vapes  batts are at 64%. removed battery.s again did the above and it stuck with temp on 85 , so reinstalled stock firmware and works fine ,now did reinstall your firmware and stuck with device to hot   at 85c now back to stock firmware

**Comment by ClockSelect** [comment]
I found a bug in temp sensing. It should work better.

**Comment by docdeath** [comment]
wheres bin file  ? to test

**Comment by ClockSelect** [comment]
[Here](https://www.dropbox.com/s/6878hw1w0ufei1t/myevic.bin?dl=1), that's always the same link.

**Comment by docdeath** [comment]
ok my bad thanks well temp problem solved now and working ok so far  only thing i cant seam to get  10 clicks for temp up 20 clicks for firmware works but 10 clicks nothing happens will keep trying as its always been hit and miss with that one as far as i can tell it all works clock works  and every thing else in menus works

**Comment by ClockSelect** [comment]
Fine, I released it. We can wait a bit for USB charging - not an essential feature on a 4 cells box, anyway.

**Comment by docdeath** [comment]
well charging it with usb is not good thing anyways  best to remove and charge in proper charger , have tested with sock firmware using usb to charge and it very in balanced so  would not use

**Comment by ClockSelect** [comment]
[New prototype version](https://www.dropbox.com/s/6878hw1w0ufei1t/myevic.bin?dl=1), with supposedly functional battery charging, including balancing.

Note about balancing: the box balances the load at *end of charge*, that is when one of the cells has been fully charged and others are still late. Half-charging will not balance. Balancing should set cells within 0.03V from each others.

Testers needed.

**Comment by ClockSelect** [comment]
@docdeath Did you test this one?

**Comment by docdeath** [comment]
@ClockSelect  AM testing at moment  will let you know asap

**Comment by docdeath** [comment]
@ClockSelect  it all seems to be working as it should  not fully charged  as yet but  battery's are  close to each other tested with dig volt meter .04 will give full charge tomm and see if any changes

**Comment by docdeath** [comment]
@ClockSelect fully charged 30q Samsung with all battery's with in 0.5 off each other

**Comment by ClockSelect** [comment]
I hope you meant 0.05^^
Thank you!

**Comment by Riadner** [comment]
Does it works with RX2/3 or RX200S?

**Comment by ClockSelect** [comment]
RX2/3 and RX200S work as usual. Cell balancing is specific to the RX300.

**Comment by Riadner** [comment]
So RX300 has balancing IC?

**Comment by ClockSelect** [comment]
Sort of
