### ISSUE TITLE
Suggestion : logo/image on charging screen

### ISSUE THREAD

**Issue by popokoplo** [ClockSelect/myevic#241]
maybe it will more exciting if there is an image when the device was charging. i found this patch on evic vtwo mini 4.02 firmware.

thx, for make this awesome firmware :)
![pic_dog7](https://cloud.githubusercontent.com/assets/25015424/21780165/1cb5083e-d6dd-11e6-97c6-ae2849e7440d.jpg)

**Comment by ClockSelect** [comment]
It would imply to have an image loader software for that purpose.
This doesn't exist at the moment.

Should be doable with the logo, though.

**Comment by ClockSelect** [comment]
I'll just make an empty picture in the image db you could change to whatever you want, simpler option.

**Comment by ClockSelect** [comment]
You may upload a picture in the character #0xFF of the font.
If something is present, it will be used as the loading screen.

Use VTCFont or NFirmwareEditor to import an image.
