### ISSUE TITLE
puff counter digits

### ISSUE THREAD

**Issue by vendeghlajos** [ClockSelect/myevic#243]
Hello, 
in the next relase could you make a modification of the puff counter numbers please:
insted of 00099 it would look much better only 99.
Thank you!
Lajos

**Comment by ClockSelect** [comment]
Why not.

**Comment by vendeghlajos** [comment]
Thanks!  I think would be more clean the UK without those unnecessary zeros!

**Comment by vendeghlajos** [comment]
Thanks!  I think would be more clean the UI  without those unnecessary zeros!

**Comment by ClockSelect** [comment]
I agree, but it looks a bit empty when numbers are small^^
