### ISSUE TITLE
question? how can i copy my config to other battery

### ISSUE THREAD

**Issue by acevalsl** [ClockSelect/myevic#247]
hi, how can i transfer my config from vtwo mini to other vtwo mini identical........??

thxs

**Box Model:**vtwo mini

**Coil setup:**vaporesso ceramic

**Comment by ClockSelect** [comment]
By using a tool such as [NFirmwareEditor](https://github.com/TBXin/NFirmwareEditor/releases), you can read and write the Dataflash from and to a file.

**Comment by acevalsl** [comment]
i am using that tool but nothing happend.
flirt read old vtwo, and next write new vtwo with file created in firs step, but no copy nothing.
i tried nfirmwaretool and nfetool box

**Comment by ClockSelect** [comment]
The two boxes should also run the very same firmware version, but I assume it's obvious.
It *should* work; I can't really help you there. I've no two identical boxes so I can't test by myself.

You could also use [Ban3's python-evic](https://github.com/Ban3/python-evic) as a command line tool if you're on Linux.

**Comment by acevalsl** [comment]
all same but nothing.
i am using os x
i am going copy parameters by hand.
no problem


![img_2774](https://cloud.githubusercontent.com/assets/22813078/22074657/687b34dc-dda9-11e6-8112-0d7b66e0c213.JPG)

**Comment by ClockSelect** [comment]
Nice couple :)
