### ISSUE TITLE
Option for MXJO IMR 18650F 3000MAH 35A Battery in Expert Menu

### ISSUE THREAD

**Issue by nbraunstein** [ClockSelect/myevic#255]
I see options for the LG HG2, most seem to be 2500mah batteries. Can we have the MXJO IMR 3k added to the available list?

**Box Model:** RX 2/3

**Coil setup:** .20 dual 316L fused claptons

**Comment by ClockSelect** [comment]
MXJO does not make batteries.
Your MXJO is a rewrapped (LG/Samsung) with AT MOST 3000mAh.
If you know what really is under the wrap of your MXJO, it's already in the configurable options.
HG2 is a reasonable guess.

myevic only support (sort of) batteries from battery producers, not battery rewrappers.

**Comment by nbraunstein** [comment]
Good to know :)
    
  
 Sent from my iPhone, please excuse any syntax errors.     

  
  
  
  

  
  
>
