### ISSUE TITLE
VTWo Mini don't work

### ISSUE THREAD

**Issue by npocmogu** [ClockSelect/myevic#26]
With the new version of firmware VTwo Mini (not VTC Mini) does not work. After upgrading black screen and nothing more. Previous versions worked fine.

**Comment by Johnny147** [comment]
I have injected the new firmware (tryied the official and this oneà and they are working right on my Vtwo Mini Hardware version 1 and I had the same firmware.
Maybe try with the latest Joyetech updater ? And unlocking box after ?

**Comment by ClockSelect** [comment]
That's weird. New version _sloved_ freezing problems.
Unfortunately, I don't have a VTwo anymore to test thing. And anyway, the VTwo I had worked fine.

**Comment by ClockSelect** [comment]
I'm afraid someone with a freezing VTwo will have to investigate on this by himself...

**Comment by maelstrom2001** [comment]
@ClockSelect Check line 226 in myrtc.c
It should be `if (!--rtccnt)`
We tried it with npocmogu yesterday and it works for VTwo Mini :)

**Comment by ClockSelect** [comment]
You're right.
Well done!

**Comment by ClockSelect** [comment]
Anyway, it means your VTwo has an issue with the RTC.
As I've seen on various forums (including Joyetech's), it seems to be a fairly common issue. Hardware misconception.
