### ISSUE TITLE
Digital Clock

### ISSUE THREAD

**Issue by Johnny147** [ClockSelect/myevic#27]
Hello,
Could you place a Digital Clock instead of the analog as screensaver ?
Juste like the digital mod on 4.02
This is the patch but I can't apply it to your 3.03 mod :)
https://github.com/TBXin/NFirmwareEditor/blob/master/src/NFirmwareEditor/Patches/Evic%20VTwo%20Mini%204.02/4.02_DClock.patch

I am addicted to your mod myevic and the only missing feature is the digital clock/date and I would be so happy to have it but don't know how to do it myself.
If possible... A big thanks !

**Comment by Daveee10** [comment]
Now I'm working on it

**Comment by Johnny147** [comment]
Thanks that's so nice ! It gonna be the perfect firmware :D
Regards

**Comment by Daveee10** [comment]
Now your request is ready

**Comment by Johnny147** [comment]
Thanks again :D !!!
