### ISSUE TITLE
No difference between 58% and 100% screen contrast?

### ISSUE THREAD

**Issue by javak810i** [ClockSelect/myevic#298]
Hey, 
In the screen contrast (brightness) settings I noticed that there's no difference between a setting of 58% or 100% meaning that the brightness maxes out at 58% and doesnt increase after that. Is that normal?

Box Model: Joyetech Evic VTwo

Coil setup: doesnt rly matter

**Comment by dywersant** [comment]
Yep, thats how this oled screen works, nothing we can do about it.
