### ISSUE TITLE
power curve erase all times

### ISSUE THREAD

**Issue by acevalsl** [ClockSelect/myevic#305]
hi, every time i change battery, loss my curve.
i tried with my two models..... evic etc mini and vtwo mini.
when install previous firmware all is ok like firmware  ClockSelect [#206] Preheat Delay applies to power curves, but with finals firmwares not work. loss power curve.

txs

**Box Model:**
vtwo mini[#248] Fix end of power curve
vtc mini[#248] Fix end of power curve

**Coil setup:**
vaporesso ceramic coil

**Comment by 360up** [comment]
I lose power curve settings on vtc-mini w/o even changing battery.

**Comment by ClockSelect** [comment]
That's right, power curve is incorrectly checked at startup and reset.

**Comment by ClockSelect** [comment]
No news, good news.
