### ISSUE TITLE
oddball glitching with certain 3D objects

### ISSUE THREAD

**Issue by Gartral** [ClockSelect/myevic#308]
on the evic vtc mini the Dodecahedron and Icosahedron glitch out hilariously after the firmware has been first applied, but after some hours they fix themselves mysteriously, I'll have to check the reproducibility of this and monitor for the amount of time it takes to fix itself..

In my humble opinion this is a low priority bug.

**Box Model: Evic VTC-Mini

**Coil setup: N/A

**Comment by ClockSelect** [comment]
Have you made some progress in your research? :D
