### ISSUE TITLE
[enhancement] allow profile removal

### ISSUE THREAD

**Issue by 360up** [ClockSelect/myevic#311]
Please allow the complete removal of a profile in order to cycle through configured ones quicker

**Comment by tharealgc** [comment]
Requested this months ago, Clock told that he will think about it and it should be available at some point... not yet tho, hope this gets updated soon and that Clock has time to deal with this.

**Comment by ClockSelect** [comment]
Done.

**Comment by tharealgc** [comment]
Thank You!
