### ISSUE TITLE
Bugs with current firmware on RX300

### ISSUE THREAD

**Issue by davidthedopest** [ClockSelect/myevic#323]
The voltage on the RX300 tends to draw unevenly between the 4 batteries along with not reading the batteries voltage correctly even when corrected in expert settings.
Coil setup is a dual SS316 twisted .145ohm at 100w running 215°C running 25r batteries (new and used).

**Comment by USA-RedDragon** [comment]
Duplicate of https://github.com/ClockSelect/myevic/issues/291 (Which has a fix)
Also see https://github.com/ClockSelect/myevic/issues/322

**Comment by davidthedopest** [comment]
Thanks! My bad
