### ISSUE TITLE
Modding X32 in VTC-Mini?

### ISSUE THREAD

**Issue by fld** [ClockSelect/myevic#327]
```
X32
...
*This option is useless and forced to "OFF" on boxes known not to have an X32 crystal. Those are all boxes for which the manufacturer did not enable the RTC feature, i.e: VTC-Mini, Cuboid/Mini, Presa 75W and RX series.*  

```
I noticed in a teardown video of [VTC-Mini](https://www.youtube.com/watch?v=iHTW6KXxDnQ&t=203s) that there is an empty footprint on the PCB, supposedly for a 32.768kHz crystal. If somebody decided to add that in, then shouldn't there be a way to enable it in the firmware?

**Comment by pharmaka** [comment]
if you were to solder a crystal to the pcb, id say you can also recompile the firmware with the option to have it active. certainly possible but not necessary as an option in the standard firmware imo
