### ISSUE TITLE
Disabling clock on main screen RX2/3?

### ISSUE THREAD

**Issue by KranV2** [ClockSelect/myevic#329]
Sorry for posting this here if it's not really an "issue", so I apologize.
But I've gone through almost every single option on my rx2/3 menu and I CANNOT find how to get rid of the large clock on the main screen, that only goes away once you hold the fire button. (Then comes back when I let go), I kinda wanna see my values regardless of button press so any insight on where this is to disable it? Potentially a bug but I'm doubtful, many thanks.

**Comment by MicroSur** [comment]
Menu / Interface / Clicks
Choose clock call on fire clicks count, exit menu and then click fire button this times.
Then you can bring back your own clicks options.

//  [my conception of myevic here](https://github.com/MicroSur/sur_myevic)

**Comment by KranV2** [comment]
Many thanks, and apologies for the late reply.

**Comment by ClockSelect** [comment]
By default, a double fire click will switch clock display on and off.
