### ISSUE TITLE
Info on splash screen

### ISSUE THREAD

**Issue by enricorov** [ClockSelect/myevic#339]
I'm sure it's been posted before, but I couldn't find anything on the topic. 

I've been using openevic for a while, and liked the splash screen showed when powering on the box (5 clicks). I remember reading that feature had been implemented before the fork. How do I include my own?

**Comment by MicroSur** [comment]
>How do I include my own?

With FW Editors. My VTCFont or NFE.

**Comment by enricorov** [comment]
Thanks a lot, I'll do that.

**Comment by enricorov** [comment]
For all those having my same problem:

- Download the latest evic.bin file
- Get VTCFont, and load the .bin
- The splash screen in question is at location FF, scroll the left bar until you get there
- Edit it as you please
- When done, press 'Save all'
- Flash the .bin file with your tool of choice
