### ISSUE TITLE
Wismec RX200S - RX2/3

### ISSUE THREAD

**Issue by bluenazgul** [ClockSelect/myevic#36]
Hi ClockSelect,

Would it be possible to create an Custom Firmware (maybe called myRX) like your myevic for the Wismec RX200S - RX2/3?

Maybe it is possible to get the source for the Firmware the Same way you got it for the VTC.

Kind regards
Andre

**Comment by ClockSelect** [comment]
It's almost the same code, so technically the source is there... almost.
There's only a few hardware changes between the VTC and the RX200S and the myevic firmware _could_ be made compatible with the RX200S; not an obvious task, but doable.
I don't know about the RX2/3 (didn't look at the code yet) but if it's doable for the RX200S, the RX2/3 should not be a big deal either.
Unfortunatly, I do not own any of those boxes, so it would be a bit difficult to test.

**Comment by bluenazgul** [comment]
Sounds great, i believe If you offer a closed "Alpha" or "Beta" there will
be many tester, i am Admin of two German FB groups and I now there are a
lot User who allready asked for an RX200S Version.

**Comment by DumanAlti** [comment]
Here, im the second voluntary ;)

**Comment by Tomish666** [comment]
Yesss...here is the third voluntary! Please make it true!😀👍🏻

**Comment by Lory82** [comment]
I'm the next :-)
a Custom Firmware like "myevic" for the Rx200S and other models need the user. Plesse :-)

**Comment by ClockSelect** [comment]
I'd prefer one of the most enthusiast of you pulling a branch from the current project and trying.
I may give you hints to do this.
For example, for the RX200S:
- Shunt resistance is 110 mOhm
- Display is SS1306
- There is 3 measures of battery voltage:
  -    ADC18  BATT VOLTS 1
  -   ADC0    BATT VOLTS 1+2
  -    ADC4   BATT VOLTS 1+2+3
  
  Batteries are serial, so the three ADCs mesures cumulatives sum of voltages.
- There is no Boost Converter for atomizer; PWM2 is replaced by a second buck converter running in parallel when firing. PWM0 alone is used for atomizer probing.
- There is a Boost converter (PWM5) used to boost voltage from USB port to battery for charging. ADC 3 and 13 are used to control battery charge.
- There may be some more things but I did not took much time to investigate.

Not obvious, I said.

**Comment by ClockSelect** [comment]
Let's make it short: I do not need a tester, but a developer^^
Whit the box by hand.
Sure testers will be welcome and necessary. After^^

**Comment by chris180389** [comment]
Here is a devloper with a Box in the Hand! ^^

**Comment by ClockSelect** [comment]
Fine!
I encourage you to fork the project, create a branch, and... Let's try! :)

**Comment by bluenazgul** [comment]
@chris180389 do you allready have a new branch created yet?

**Comment by ClockSelect** [comment]
I had a look at the cuboid, and it's very close in its hardware to the RX200S.
I do not own a cuboid either, so it doesn't advance the schmilblick very much, but I'm pretty sure the Dual will be very similar, and I'm waiting to buy one.
Once I have it in hand, things may be more clear.

**Comment by maej72** [comment]
so you will try to mod the vtc dual and the rx2/3?

**Comment by ClockSelect** [comment]
Dual, sure. rx2/3 & others rx will depend on my success with the dual.

**Comment by bluenazgul** [comment]
@chris180389  @ClockSelect any Progress here?

**Comment by ClockSelect** [comment]
Should have my Dual within days.

**Comment by bluenazgul** [comment]
Sounds great @ClockSelect sadly i cant test on Cubiod anymore, but still able to test on VTCmini / RX200S and RX2/3

**Comment by afol2** [comment]
I have a Cuboid Ready to test, shouldn't be the same as the VTC Dual ? as it have 2 batteries. Also i have another question, it is known that the cuboid have a Hard Lock on the amp @ 25 making it almost useless at less than 0.3 ohms, this is something that can be bypass ?

**Comment by ClockSelect** [comment]
@afol2: Unfortunately no; the 25A is a hard limit, as are the 9V. You have to tweak the rez value to get the power you want.

**Comment by bluenazgul** [comment]
Would be a dream that out AT's would Detect the used Batteries (but that
wont work).

I remember that there was an unofficial and non public patch für the Cuboid
to change the Ampere Limit.

I only use Sony VTC4 so 30A are safe for the.

**Comment by afol2** [comment]
Hmm... that could be like something that could be added in >Expert Mode< some kind of tweak that allow you to change the Ohm value , even tho it is lower. it also can have like some kind of warning to just uses recomended tested batteries 30 amps, Like LG HB6. @ClockSelect

**Comment by afol2** [comment]
Or that you have to select in Expert>Batt>HB6 in order to allow the tweak @ClockSelect

**Comment by Filo301** [comment]
It's 25A limit on output, not input. Maybe just dc-dc can't handle more.

**Comment by ClockSelect** [comment]
Output values are limited to 9V and 25A.
Put together, it's a power of 5625W, which, IMO, should be enough for anyone here.
The very limiting factor is the power limit enforced by the software (75W, 150w, etc depending on the box), which in turn limits the volts/amps accordingly.
The drain on the battery does not depend on the volts/amps sent to the atomizer by the dc-dc; it's only a function of Power (given the dc-dc effciency, say 90%) and battery internal resistance.
At a given power setting:
0.9 \* P = ( U \* I - r \* I² )
With U = idle battery voltage, I = battery drain, r = battery internal resistance.
Solve this equation and you have the battery drain.
I = ( U - sqrt ( U² - 3.6 \* r \* P ) ) / 2r
If you do the math for a single-cell box, given a 75W limit and an internal resistance of 30mOhm, it gives you a battery drain limit of around 23A at 3.6V, which is reasonable.
If you think your battery can go up to 30A with no issue, you could, theorically, set your power limit up to 90W.

**Comment by ClockSelect** [comment]
Oh, by the way: I've been lent a Cuboid a few days, so...
Now we have the Cuboid :)
This opens the way to others multi-cells boxes, but I can't implement a new box without having it by hand. Multi-cell management is complicated and no two boxes do this the same way.
Next to come should be the VTC Dual, and after... It depends on which boxes I can borrow to someone^^

**Comment by bluenazgul** [comment]
Stock Limit on RX200S and RX2/3 is set to 50 Amps by Wismec.

So i would say the "custom Firmware" should keep this limit, as there are
no Batteries that have this limit.

**Comment by bluenazgul** [comment]
@ClockSelect is there a way to contact you private? Iam Admin of the
biggest German speaking RX Facebook Group, maybe there could be a way to
lend you a Box ;)

**Comment by ClockSelect** [comment]
@bluenazgul
Sure! Give me the link to your group and we'll talk via FB.
(But I wouldn't be surprised I'm already a member)

**Comment by ClockSelect** [comment]
50A on the output side. Use the formulas, you'll see it's still around 20A on the battery side. Cells are in series, you have three times the voltage.

**Comment by bluenazgul** [comment]
@ClockSelect

Here is the Link ;)
https://www.facebook.com/groups/WismecRX200DE/

**Comment by bluenazgul** [comment]
@ClockSelect as promised my Parcel is on the way to you ;)

**Comment by ClockSelect** [comment]
I will try not to burn them^^

**Comment by afol2** [comment]
so, i was wondering if you find a way to overcome the 25amp limit in the cuboid ?

**Comment by ClockSelect** [comment]
Overcoming limits is easy; I more or less just have to change a number somewhere. Problem is: how do I know the actual box limits before failure? The only thing I can be sure of is that the limits enforced by the factory firmware are on the safe side, but remember that it's chinese cost-effective conception. Hardware limits must not be _that_ far.  
Remember that your 25A do not pass only throught the atomizer; they also go throught a tiny 1.x milliOhm shunt resistance, and that's already at least .62W for her to dissipate; it's huge for such a tiny component. I don't know the dissipation limit of this resistance, but again, they may not have taken a 100% margin (maybe a 1W thing).
The 3-cells reuleaux have a higher limit (50A, iirc), but they have _two_ parallel shunts to measure atomizer current. So it make me think the margins are not so large.  
I'd like to avoid issues like "my box is dead", so for know I don't play too much with the numbers.

**Comment by ClockSelect** [comment]
Well... Here we are.
Maybe the more adventurous of you would give it a try :)

**Comment by Filo301** [comment]
@ClockSelect  What you exactly need to know about rx2/3 to support it?

Sorry for my bad English.

**Comment by dywersant** [comment]
Testing now, so far so good. Great piece of software.

**Comment by dywersant** [comment]
Btw you can flash rx200s with rx23 firmware. Tried that, everything worked fine. So supporting rx23 shouldnt be much of a problem.

**Comment by ClockSelect** [comment]
RX2/3 firmware handle more things than the one of RX200S, so flashing the first in the second may work fine (albeit it's absolutely not recommended), but not the other way.
If you'd try (don't!) to flash the fw of the RX200S in the RX2/3, it couldn't handle correctly the dual-cell configuration, for exemple. It could just fail, or, do bad things.

I must thoroughly examine the fw of the RX2/3 to spot and reproduce all the tiny difference it may have in battery and chipset management. It will take some days.

**Comment by Filo301** [comment]
If you need pics of pcb etc. i can make it. I also have pics of rx200s pcb so we can compare it.

**Comment by ClockSelect** [comment]
Yes, if you have good quality pics, I'll take them. It may help sometimes.

**Comment by Filo301** [comment]
Interesting.... Almost the same. I don't have more 200s photos.
23: https://imgur.com/a/MIiSW
200s: https://imgur.com/a/c8Hya

**Comment by ClockSelect** [comment]
That's what I though, MCU is under the screen. That's an essential part; on the picture with the screen removed, we only see half of the pins of the MCU. There's something on it hiding the 12 top and 12 bottom pins.
Can this part be safely removed?

**Comment by Filo301** [comment]
I already assembled it. Please, wait a while.
E: Little bit dark, sorry for that:  http://imgur.com/sW3jbZv

**Comment by ClockSelect** [comment]
That's it, grats.
Can't see right now if I can retrieve the full size pic from Imgur since I'm on my phone; I'll examine all that when I'm back.
Thank you!

**Comment by Filo301** [comment]
I upload it on MEGA, full size photos. https://mega.nz/#F!U5wzDDID!WP5WfFAV4MitiKFACk5QOA
Thank you for awesome software!

**Comment by ClockSelect** [comment]
Precious.
Hope they won't be needed.
But they're here.

**Comment by ClockSelect** [comment]
Today's release was awaited...
![](https://www.dropbox.com/s/yoke8w7n9jouyid/visitors.png?dl=1)

**Comment by afol2** [comment]
RX200S is the same as for the RX2/3 ? @ClockSelect

**Comment by bluenazgul** [comment]
@afol2 it is not the same - RX2/3 is still work in progress

**Comment by afol2** [comment]
@bluenazgul oh ok.!, thanks

**Comment by bluenazgul** [comment]
@ClockSelect Here are some Pictures of the RX2/3 Mainboard - i hope they
could help you

**Comment by bluenazgul** [comment]
@ClockSelect has my RX2/3 on his Desk ;)

**Comment by bluenazgul** [comment]
@ClockSelect A friend has two RX2/3 disambled right now (for FatDaddy mod
;) ),  he will send me Pictures later today

**Comment by e0x** [comment]
the recent commit say support RX200S , anyluck that this can work in the RX200 too ?

thanks

**Comment by Filo301** [comment]
@bluenazgul I aleready uploaded some photos.
@e0x Main problem is different oled, same as istick pico.

**Comment by e0x** [comment]
@ClockSelect make sense , thanks anyway.

**Comment by ClockSelect** [comment]
Enjoy! :)

**Comment by Tehnik45** [comment]
Привет ClockSelect,RX200S, after flashing boxing from the start temperature of 38 degrees, 3-5 puffs and the temperature 53-56 degrees, any ideas why?

**Comment by Tehnik45** [comment]
RX200S, and insert the battery box temperature with cold 28 degrees itself rises to 38-40, and that no steaming !? What to do, help!

**Comment by Tehnik45** [comment]
RX200S, and insert the battery box temperature with cold 28 degrees itself rises to 38-40, and that no steaming !? What to do, help!

**Comment by falconettt** [comment]
Confirm that the temperature is increasing, it is not normal, need something to do with it. This was not on the original firmware.
RX2/3

**Comment by Tehnik45** [comment]
The official firmware did not notice, because I had to do 10 clicks to see, and now we can see on the screen all the time, but a spontaneous rise in temperature is, when you install the battery goes the temperature rise from 32 to 39 for 2-3 minutes! Sorry for my English, I write through a translator

**Comment by ClockSelect** [comment]
Board temp reading is highly inaccurate.
Just there, I have an RX2/3 on my desk; untouched since a few hours. Temp shows 27°C. I press a button and it jumps to 36°C with no real temperature change (still perfectly cold).
I wouldn't rely too much on the displayed number. Do you _feel_ the temp increases? 40°C is damn hot. Can't miss it.

**Comment by falconettt** [comment]
Yes, it "damn hot" and more than 45°C on the screen in passthrough mode, 2 bat.  RX2/3
It seems liquid get overheated.

At the same condition it's not hot and no more than 39°C on the screen with evic mini

**Comment by falconettt** [comment]
It seems to me you tried to make usb charging faster. It turned out faster but damn hot.

**Comment by Tehnik45** [comment]
At the touch of boxing is not very hot, if not the reading on the SCREEN I would not pay attention, it quickly heats up but quickly cools, and you can ProFIX heating temperature? Yes, the batteries are charged only with the charger.

**Comment by ClockSelect** [comment]
USB charging is the same as the original firmware. It charges at twice the max amps than the single-cell boxes so yes, it may be a little warmer, but should get nowhere near 40°.
I think your real problem is having a number on the screen you hadn't before.
You can read the temp on the original firmware by switching off the box and clicking 10 times on the fire button. Would be surprised if you get different readings.

**Comment by Tehnik45** [comment]
Boxing does not alter the official firmware, it requires an increase in

**Comment by falconettt** [comment]
I swear ^^
I don't vape, usb charging, temp is 40 C
 If I vape while charging - temp is above 45 and it is not comfortable.
It is not a little less comfortable it significantly LESS COMFORTABLE as on evic mini.
(Why i bought this damn shit RX, it would be better to buy charger and a couple of spare batteries...)

May be good idea to have two usb charging profiles: 
First is hot and fast but vaping prohibited.
Second is cold and slow but vaping is comfortable.

**Comment by e0x** [comment]
@Filo301 @ClockSelect sorry for be here again asking maybe useless question , but what is need for this firmware work in RX200 is port the menu to a screen form factor of the RX200 or need something else ? for your experience how hard can be this ? i have a lot of free time but i don't have much clue about C or C++ but i have a little bit experience in other language so i have a idea of what programming is so i think maybe i can give a try . 

disclaimer i suffer/have/choice/select  from  procrastination a lot so ppl don't hold your breath for this or light any hope about this.

**Comment by ClockSelect** [comment]
It's not highly complicated, but really cumbersome.
You'd have to rewrite the whole screens drawing part and some of the event management parts, along with the whole menu system which is inadapted to a small display.
Also, the communication with screen controler is different and requires to rewrite some of the display hardware part too.
Technicaly, the RX200 is an triple-cell Eleaf box. If you rewrite the firmware for the RX200, you'll also have rewritten it for the TC100W, the Pico, etc.

**Comment by e0x** [comment]
thanks !

**Comment by Villista** [comment]
Unfortunately when trying to load the logo with dimensions different from 64h48 on the RX2 / 3 Editor automatically resize to the specified size !!! Can I download the logo of different sizes and how to do it?

**Comment by bluenazgul** [comment]
@Villista its a know issue, we would need an universal Updater with Variable Logo Size support

**Comment by Villista** [comment]
And where can I get such a universal updater? It's a secret? :-)

**Comment by bluenazgul** [comment]
Sadly we dont have one yet

**Comment by Villista** [comment]
Good time to all! Switch the screen in the "Inversion-On" mode and was surprised that the screen remains switched on continuously in white. I think that it does not save battery power. To restore the burned pixels will be enough inversion in information display only (if someone wants to, then turn on the "snow" screen saver option). I think the screen should fade to black in any mode "Inversion On / Off". Correct me if I'm wrong?

**Comment by ClockSelect** [comment]
That's what is does. It fades to black, but since it's inverted, it shows white^^
Only when it switches off (in sleep mode) will it go to black. That's after 3 minutes of inactivity without screen saver or at the end of screen saver duration (or when you switch the box off).
Max power consumption of pixels is 100µA/line, that's 12.8mA for a full white screen at 100% contrast (half of that at 50% contrast and so on).
So yes it's not neglictible.

**Comment by visokiyd** [comment]
Hi. can't connect rx 2/3  to the computer after the firmware. Is charging but the firmware can't install help me please

**Comment by visokiyd** [comment]
In Expert usb Hid

**Comment by Villista** [comment]
@visokiyd Try to pull out the battery and remove the tank. And then connect to computers.

**Comment by visokiyd** [comment]
@Villista all versions I've tried
