### ISSUE TITLE
evic vtc mini 75 w

### ISSUE THREAD

**Issue by kae64** [ClockSelect/myevic#41]
Good afternoon.
 After flashing EVIC VTC mini 75w firmware from the folder bin - myevic_enc.bin (3.10, https://github.com/ClockSelect/myevic)- It pierced through a file of official firmware, then there is no formal regime titanium and S316.
And sews through emergency vostanovlenie (+ clip, and then connecting yusb), using officially 1.02 does not restore modes.
 The official firmware 3.0, 3.01 all modes. -  poower - yes/bypass - yes/start - yes/tempni - yes/temp Ti - yes/ ss316 - eys/tcr - yes/
 Starting with firmware 3.02 mode of titanium and 316 missing. -   poower - yes/bypass - yes/start - yes/tempni - yes/temp Ti - no/ ss316 - no/tcr - yes/
 When you reinstall - myevic_enc.bin -   poower - yes/bypass - yes/start - yes/tempni - yes/temp Ti - no/ ss316 - no/tcr - yes/ - the firmware on your flash when you turn on in the settings, they are not displayed when you switch. included exposing yes, does not help in the menu.
Help solve this problem.
 Sincerely, Alexander

**Comment by kae64** [comment]
Installed firmware from joyetech (+ clip, and then connecting the USB), using officially joyetech 1.02 mode does not recover all of the modes. The other user in the same way everything turned out. That is, when you return to the firmware of the titanium are not available mode and ss316.

**Comment by Daveee10** [comment]
When you see temp ni press the minus button then you can change the ni mode to ti and ss316 with the plus button seems like tcr mX changing

**Comment by kae64** [comment]
titanium and steel are not available in full on the official firmware 3.02 or higher.
Prior to the shutdown , these modes are available . If you turn them off in the settings to re-enable them does not work. They are not available in the firmware 3.02 and above

**Comment by kae64** [comment]
Daveee10 . 
Your proposal only changes the temperature

**Comment by kae64** [comment]
Such errors are seen in many users have installed 3.10

**Comment by Daveee10** [comment]
No... You don't know how the officially firmwares work..
1. Three click
2. Plus button for go temp ni mode
3. Minus button for change select sub mode
4. Plus button for change to ti or ss316 mode
5. Press fire for confirm your selection
6. Be happy

**Comment by kae64** [comment]
This I know . None of these modes when switching . They disappeared after applying the custom firmware .

**Comment by kae64** [comment]
Firmware https://github.com/ClockSelect/myevic/tree/master/bin not working. I wonder who so tried. A lot of mistakes. Who will advise on how to reset the way to the good state.

**Comment by Daveee10** [comment]
That's working... Now I'm using that...

**Comment by kae64** [comment]
very bad work in the power jumps resistance mode, after the first shutdown mode again they are not already included. This is bad. Very bad

**Comment by kae64** [comment]
And still I restore my fashion work.

**Comment by kae64** [comment]
![20160920_213717](https://cloud.githubusercontent.com/assets/22319622/18684093/9cad5fe6-7f7b-11e6-948e-21ec29877631.jpg)
![20160920_213731](https://cloud.githubusercontent.com/assets/22319622/18684098/a4fa4c0e-7f7b-11e6-81c4-b854ec17a737.jpg)
![20160920_213745](https://cloud.githubusercontent.com/assets/22319622/18684107/ab1f62f4-7f7b-11e6-8e37-41a60072f74f.jpg)
![20160920_214007](https://cloud.githubusercontent.com/assets/22319622/18684117/b355bb4e-7f7b-11e6-98c7-4c871f568de4.jpg)
![20160920_213812](https://cloud.githubusercontent.com/assets/22319622/18684126/b973f1a8-7f7b-11e6-9558-4dcce2fcf339.jpg)
temp Ti - no/ ss316 - no

**Comment by Daveee10** [comment]
Maybe my fault but in this firmware everything works fine... I don't use official because this is better....
Check my gallery:
http://imgur.com/a/u8yVl

**Comment by kae64** [comment]
Please give your firmware on my mail kae64@live.ru

**Comment by Daveee10** [comment]
Why don't download from ClockSelect's myevic tree?? bin folder - myevic_enc.bin file
This is the link: https://github.com/ClockSelect/myevic/blob/master/bin/myevic_enc.bin

I use this on my VTC and my build on Presa... This 2 mods working very well with this FW....
IMHO you can close this issue because the report is false..

**Comment by kae64** [comment]
The program is installed on my mod, but not one button is not working
![20160920_222218](https://cloud.githubusercontent.com/assets/22319622/18685487/e9cb189a-7f80-11e6-9d85-f19c6a0f44d9.jpg)

**Comment by maelstrom2001** [comment]
https://youtu.be/ice0nopNUwU?t=3m59s

**Comment by kae64** [comment]
maelstrom2001 A huge thanks , flashed 3.03, it works. )))
The issue can be closed
