### ISSUE TITLE
Third line screen saver

### ISSUE THREAD

**Issue by Daveee10** [ClockSelect/myevic#43]
When the main screen protection settings on 5s or 10s and modifying the third line info the device can go to screen saver screen...

**Comment by ClockSelect** [comment]
Right.
As a workaround before I fix it, when the screen saver pops up, just click fire button once and you'll come back editing your item.

**Comment by Daveee10** [comment]
Thx, I know that..

**Comment by ClockSelect** [comment]
Yeah. Editing mode as a timeout of 10s, and it's supposed to always be shorter than the duration of the main screen. _thinking_

**Comment by ClockSelect** [comment]
Thought.

**Comment by Daveee10** [comment]
THX! Now fine. IMO the issue is solved!
