### ISSUE TITLE
Issue with the battery in TC mode

### ISSUE THREAD

**Issue by vhsw** [ClockSelect/myevic#44]
On fully charged battery after pressing the fire button in TC mode the battery voltage drops below 3.10 volts for a second and my VTCmini reports "weak battery". Then the battery percentage gradually returns to real value.

**Comment by ClockSelect** [comment]
Your battery is dead.

**Comment by vhsw** [comment]
Nope. Battery works perfectly on stock firmware.

**Comment by ClockSelect** [comment]
That's weird; battery management is unchanged (yet) regarding the stock firmware and there should be no difference. I never experimented your problem (I mostly vape in TC, even on my RTAs).
Could you give me more information about your setup and settings?
Also tell me your battery brand and model.

**Comment by vhsw** [comment]
Pls, close the issue, problem gone after reinstalling firmware in safe boot mode (connecting device with right button pressed).
