### ISSUE TITLE
Please tell me how to reset the counters.

### ISSUE THREAD

**Issue by falconettt** [ClockSelect/myevic#46]
hello,
Please tell me how to reset puff and time counters.
I've not found it in your "readme".
The usual way does not work (when you hold Fire during flashing counter).
Evic mini
thanks/

**Comment by falconettt** [comment]
Evic mini

**Comment by maelstrom2001** [comment]
Press and hold + and - buttons simultaneously while counter is flashing.

**Comment by falconettt** [comment]
yes, it works, thanks
