### ISSUE TITLE
eVic VTC mini - problem with connection to NFE configuration

### ISSUE THREAD

**Issue by Dareksa** [ClockSelect/myevic#47]
eVic VTC mini HV:1.01 after update to latest version (23092016) can't connect to NFE Edition-Configuration, hangs on downloading settings.
With myevic_fork firmware everything works properly so it looks that problem is not related to hw.

**Comment by sir-miro** [comment]
I have the same problem HV:1.00

**Comment by Dareksa** [comment]
With eVic VTwo Mini firmware works OK.

**Comment by sir-miro** [comment]
so we're waiting

**Comment by ClockSelect** [comment]
I works well with the binary currently available (on my VTC mini), but I know sometimes NFE as problems downloading settings. Sometimes restarting NFE works, sometimes reflashing the firmware works. I fact I don't really know what works or not^^ But eventually, it works.

**Comment by Dareksa** [comment]
I tried restarts NFE, and I reflashed vtc mini a few times but I have still the same problem with your firmware.

**Comment by ClockSelect** [comment]
Being stuck on the "Downloading settings..." means that NFE waits forever for the download of the dataflash. But downloading dataflash works perfectly well with other softwares, so this can hardly be an issue with the firmware.

**Comment by eVic75** [comment]
I confirm: eVic VTC mini HV:1.01 after update to latest version (23092016) can't connect to NFE Edition-Configuration, hangs on downloading settings. Restart NFE, reflash didn't help

**Comment by ClockSelect** [comment]
I just reproduced the problem, solved it by restarting NFE this time.

**Comment by eVic75** [comment]
I restarted, and restarted, and restarted... and still "Downloading settings"

**Comment by ClockSelect** [comment]
Ok. Found something: when I have the problem, if I change the Main screen dimmer timeout (in the Screen Protection menu) from 30 to 15s, it works.
Strange.

**Comment by eVic75** [comment]
From 30 to 15s?  In "Screen - Protection - Main" I've got 5 - 10 - 20 - 30 - 60s

**Comment by ClockSelect** [comment]
(or anything)
I've just added the 15 option, in fact.

**Comment by ClockSelect** [comment]
Should work, now.

**Comment by Dareksa** [comment]
Yes, now it's working :)

**Comment by eVic75** [comment]
Reflashed, got 15s option, and still "Downloading settings".

**Comment by ClockSelect** [comment]
Try reseting the dataflash?

**Comment by eVic75** [comment]
Do you mean: connect without battery with pressed right button? Yes, I tried. Then flashed and still "Downloading settings".

**Comment by ClockSelect** [comment]
No, I meant reseting parameters. Use the advanced tab of the Firmrware updater of the NFE.

**Comment by eVic75** [comment]
You're great :) Reseting dataflash helped. Thank you :)

**Comment by Dareksa** [comment]
Are you going to add temperature dominant function to your firmware in Interface/Click tab  ?

**Comment by ClockSelect** [comment]
It's in the TODO list.

**Comment by Dareksa** [comment]
OK, thanks for your help and very good work :)

**Comment by sir-miro** [comment]
Now it's working :) Good work :D
