### ISSUE TITLE
TDom - reverse action?

### ISSUE THREAD

**Issue by eVic75** [ClockSelect/myevic#48]
When I set TDom to "On" I've got:
![2016 09 23 20 19 31](https://cloud.githubusercontent.com/assets/22393437/18796961/e318da6c-81cb-11e6-8486-91b6f15c67d4.png)
When I set TDom to "Off" I've got:
![2016 09 23 20 19 01](https://cloud.githubusercontent.com/assets/22393437/18796980/f613a1e2-81cb-11e6-96d8-354d35151b00.png)
Is it reverse action or I don't understand TDom?

**Comment by ClockSelect** [comment]
Well, maybe On and Off should be switched. That's semantics^^
I'll check that out.

**Comment by ClockSelect** [comment]
In fact, it's the very purpose of TDom - regulating max power instead of temperature. Your max temp should be fixed to the temp you like to vape; the max power in TC mode acts like a preheat (and indeed is). So It's not really reversing; it's another way of making your vape more fluent.

**Comment by eVic75** [comment]
"Dominant Temperature", "Priority Power"... Yes, you were right: that's semantics... ;) I thought: temperature is dominating, so it should be bigger on screen :) Best regards.
![67491989](https://cloud.githubusercontent.com/assets/22393437/18807618/403858e6-824c-11e6-9bb4-1191f95f72bc.jpg)
