### ISSUE TITLE
Screen Recovery

### ISSUE THREAD

**Issue by NikitaAtamanchuk** [ClockSelect/myevic#52]
Hello! I really like the firmware, thank you for what you are doing.
I have an idea. On eVic installed OLED display, and the pixels on them burn out. This is especially the case in the battery meter zone. I suggest add "Screen Burn" or "Screen Recovery" mode - when device is turned off and charging, all of the pixels on the screen will be switched on and off. I think if you leave eVic work in a couple of nights mode, the brightness of all pixels will be equal :)

**Comment by ClockSelect** [comment]
I see. OLED is not plasma, so I don't know if ti'll work, but I may give a try.
I'll made a "Snow" screen saver, you'll tell me.

**Comment by ClockSelect** [comment]
Give it a try... tell me.
In my experience, Snow is the best way to recover from a burnt-out screen.
Set the screen protection time to the max and let it run.
(I don't know if contrast level helps or not - need your returns).

**Comment by ClockSelect** [comment]
And it's another cool-looking screen saver :)

**Comment by NikitaAtamanchuk** [comment]
You're awesome, thanks! The idea is to burn off those pixels that are brighter, and then slightly increase the contrast. A few days later, I'll let you know the results.
![img_9032](https://cloud.githubusercontent.com/assets/22458753/18862784/bf0bccce-8496-11e6-8054-91fada94844d.jpg)

**Comment by eVic75** [comment]
"Sno**v**" in Menus > Screen > Saver  was quite intentional or mistake? ;)

**Comment by NikitaAtamanchuk** [comment]
I also noticed it, but did not attach importance :)

**Comment by ClockSelect** [comment]
It's been corrected :)

**Comment by ClockSelect** [comment]
Made an Invert option in the Screen menu, just in case...
May help.

**Comment by NikitaAtamanchuk** [comment]
You are a genius! :)

**Comment by eVic75** [comment]
Battery charging screen is removed? Just asking ;)

**Comment by NikitaAtamanchuk** [comment]
Not yet. I think, need more time. My eVic used for 6 months.

**Comment by ClockSelect** [comment]
@eVic75: no, but it has been included in the "stealthed" screens.
You may set Stealth Off to see it again, or press fire to see batt charge.

**Comment by eVic75** [comment]
Ooo... I see :) Thanks for explanation.

**Comment by NikitaAtamanchuk** [comment]
Hello! Your innovation produce results! In the combined use "Invert" on the maximum contrast and "Snow" screensaver, the display is almost cleared from the burned pixels. However, in the battery indication area they still a little visible.

**Comment by ClockSelect** [comment]
That's awesome!
I must admit I was a little pessimistic on the subject; it's really cool if it works.
For the battery thing, don't use the battery percentage option. Since you burnt the pixels without the option, invert without also. All things must be kept equal^^
I'm happy it works. Good thing.

**Comment by NikitaAtamanchuk** [comment]
Yes, I understand :) I burned pixels in that zone when charging device every night (before I found your firmware).
I am also very happy, thank you. A little later, I make a photo of the screen.
I have a request about the battery voltage. Could you please return the battery voltage in the third line? For example, I use a conventional battery indicator, without the "v" and "%" with the battery voltage in third line.

**Comment by ClockSelect** [comment]
Things evolves.
Since I made the battery voltage available next to the battery, it becomes redundant on the third line.
What's more, there is already too much options on this famous third line; 8 different things is enough, IMO.
Users should not click 10 times to get what they want; this third line is a problem.

**Comment by ClockSelect** [comment]
I agree battery voltage on third line is useful. I restored it.
Will handle the third line problem later.

**Comment by ClockSelect** [comment]
I think I can close this issue know :)

**Comment by NikitaAtamanchuk** [comment]
I'm sorry, I forgot to upload the photo :)
![img_4804](https://cloud.githubusercontent.com/assets/22458753/19319022/936ebada-90b3-11e6-8a34-5b82e8fe8b1c.JPG)

**Comment by ClockSelect** [comment]
That's awesome!
Still need some time for the battery part, but the result is far beyond my expectations.
