### ISSUE TITLE
Setup time

### ISSUE THREAD

**Issue by greedybeef** [ClockSelect/myevic#53]
Long press fire button to save time settings doesn't work properly on last firmware version. Just next parameter starts blinking. Only "Fire and +" or "- and +" combinations allows to exit but it doesn't save settings

**Comment by ClockSelect** [comment]
Right. I screwed up the long fire event.

**Comment by ClockSelect** [comment]
Fixed.

**Comment by ClockSelect** [comment]
I always setup date & time by other means, so I didn't detect that.
Thanks for report.
