### ISSUE TITLE
Configured 2-click Fire events are triggerred while inside menus

### ISSUE THREAD

**Issue by eugenesan** [ClockSelect/myevic#57]

**Comment by ClockSelect** [comment]
Yes, I know that.
Depending on how you configure your events, that may be wanted or not.
Needs discussion.

**Comment by ClockSelect** [comment]
I think it's not a bad idea to disable those events while in menus.
Let's test it that way.

**Comment by eugenesan** [comment]
I am happy with the change :+1:
