### ISSUE TITLE
Preheat for iStick PICO

### ISSUE THREAD

**Issue by Reaper2u** [ClockSelect/myevic#58]
Dear ClockSelect

Is it possible to create a firmware for the iStick Pico with a Preheat feature like the one in your firmware?

Thank You very much in advance.

**Comment by ClockSelect** [comment]
If you mean "technically possible", answer is definitely yes.
If you mean "reasonably  feasible", I'd say no.
If you price the needed manpower, better buy 10 eVic VTwo.

Screen and interface of the Pico (or other eleaf) are so different that it'll take a tremendous work to adapt the myevic firmware to those boxes; interface and core system are highly intricate in the code.
It would take even more work to disassemble an eleaf firmware to start with.

ATM, best option seems to be a patch. Our Russian friends are the specialists of the question; I'd recommend you ask them.
