### ISSUE TITLE
S-mode

### ISSUE THREAD

**Issue by falconettt** [ClockSelect/myevic#59]
ClockSelect,
Just for fun and different experience of vaping.
Shall we try it?
Look here:
https://en.wikipedia.org/wiki/Modulation

If simple, something like this:

![smode](https://cloud.githubusercontent.com/assets/22370680/19048463/185ba94e-89af-11e6-8745-bc16ab2bebe1.jpg)

But there are more complex variants.
May be good idea to have A and T adjustable.

Also possible benefit to clean the coil.

**Comment by Daveee10** [comment]
First look this like a low frequency PWM... Some mode use 7Hz PWM modulation. Maybe 2-3Hz make feelable hot-cold points when vaping. Maybe... Or YiHi TC mode seems like this.. I think not a big work to programming this method.. But ClockSelect knows this better, because I'm not a big C programmer

**Comment by falconettt** [comment]
Yes, I mean low frequency modulation and hot-cold points should be feelable.

**Comment by ClockSelect** [comment]
Well... If someone wants to pull a branch and try for himself, why not... (anyway, anyone do what he wants). But I don't really feel enthusiast abut this project. What's the point? What would it bring exactly to vaping experience?

**Comment by falconettt** [comment]
I'm just asking for the opportunity to try...
What thermal control brings exactly to vaping experience? IMO fun for beginners. I'm happy without TC.
But you can use TC if you want.

You can't say exactly before you try.

Look, it's on the market already, with you, or without:
http://www.yourcig.com/product/balrog-ex.html

Your choice?

If you don't want to try - let's close the topic.

**Comment by ClockSelect** [comment]
Power curves have been on the market for long - Since the very first eVics.
Gonna look a review of this thing.

**Comment by falconettt** [comment]
I will try to convince you...
Нот and cold points have different taste.
Something tells me (what is it?) that this algorithm 

![as](https://cloud.githubusercontent.com/assets/22370680/19168973/0d5c53b8-8c1b-11e6-8a39-47dc907463dd.jpg)
can provide well, just a "rainbow" of tastes.
Isn't it amazing?

**Comment by ClockSelect** [comment]
That's more or less the curve of the actual VTC firmware.
One of my projects is to correct this situation, not to amplify it.

**Comment by falconettt** [comment]
So what? You did it great man? Or have I just found? However ready.
Here we are: Overregulated PID as low friquency PWM!

My mod now works like a locomotive and it is clearly audible!!

Please forgive my rude behavior. 
I have a triple overdose of nicotine as a result of the tests and that makes me "gav-gav"...

With such a toy I do not insist on power curves any more!

P-5000/I-850/D-20
![234](https://cloud.githubusercontent.com/assets/22370680/20243094/268f8a5c-a959-11e6-8ecd-5012b4857a2a.jpg)

**Comment by ClockSelect** [comment]
Indeed, you can create steady oscillations with the PID.
Didn't tought of that.

**Comment by ClockSelect** [comment]
Discussion moved to #144
