### ISSUE TITLE
Missing modes Wismec Presa 75 TC

### ISSUE THREAD

**Issue by dabugen** [ClockSelect/myevic#63]
Hi:)

Although I´ve enabled all modes in /Vaping/Modes with a "Y", in the main menu I can only select:

Power, Bypass, Smart, Temp Ni, TCR M1 (the one I am using).

What am I doing wrong?

Thank you,

Hans

**Comment by ClockSelect** [comment]
When you're on TEMP NI and TEMP in blinking, press (-) and the "NI" will blink.
Then press (+) to cycle through NI, TI and SS.
Same thing with TCR to cycle through M1/2/3.

**Comment by ClockSelect** [comment]
See video at end of issue #41 if you need more help.

**Comment by dabugen** [comment]
Thanks a lot, all good, my fault:)
