### ISSUE TITLE
Unnecessary "%"

### ISSUE THREAD

**Issue by eVic75** [ClockSelect/myevic#65]
Is this "%" necessary?
![2016 10 06 20 56 27](https://cloud.githubusercontent.com/assets/22393437/19166454/d88ca934-8c07-11e6-99e5-fa3321b5943d.png)

Best regards

**Comment by dabugen** [comment]
It means "battery percentage" and hence Batt% is absolutely right.

**Comment by eVic75** [comment]
I know what it means :) It WAS absolutely right when the options were:
**Batt% Of
Batt% Off**
Now, when the options are:
**Batt %
Batt V
Batt Off**
"Batt%" looks weird...

**Comment by ClockSelect** [comment]
Seriously... You opened an issue for this^^
I'll remove the %.

**Comment by eVic75** [comment]
Sorry, I didn't know how to let you know about it.

**Comment by ClockSelect** [comment]
Don't close the case before it's done or I may forget^^

**Comment by eVic75** [comment]
Sorry again. It isn't my good day :)

**Comment by ClockSelect** [comment]
Don't mind. :)

**Comment by dabugen** [comment]
It´s a SERIOUS problem, we should open 2 threads about it actually. My Evic almost BURNED because of this bug!!!!!!

**Comment by ClockSelect** [comment]
Finally, I didn't remove the %.
