### ISSUE TITLE
Wrong voltage/percentage battery

### ISSUE THREAD

**Issue by GittyHub22** [ClockSelect/myevic#66]
Hello, 

Just charged my battery external, it shows 4.06v and on my charger it shows 4.23v
Also my battery is a 30Q but if i use that setting in the expert menu the percentage is off. 
And if I turn my device off (Presa 75w) and connect a charge cable it shows a different percentage than when the device is turned on, no matter what setting.

And these ones are extremely minor but the cube screensaver does not work anymore since yesterday's updates I believe. I know the ml vape is experimental but that does not seem to do anything.

I hope you can do something with my findings, but you have already done a great job.

Regards,

**Comment by NikitaAtamanchuk** [comment]
Hello! I also have a problem. My HE4 in a build 161006 is charged to 4.24v or higher. I unplug the charging, because I'm afraid break the battery. Before installing this build, battery exactly charging to 4.2v

**Comment by ClockSelect** [comment]
@NikitaAtamanchuk: what's your box?

@GittyHub22: Id did not change anything in battery measurement from the genuine Presa75 firmware. Unfortunately, I do not have a Presa by hand to test; what I'd like is you to reflash the original firmware and do the very same tests about volyage, and tell me on each case how I'm off.

**Comment by dabugen** [comment]
All fine with my Samsung 30Q´s and my Presa 75 TC here with the voltages. Also the battery % display matches when on / off and connected to the USB charger.

**Comment by ClockSelect** [comment]
In theory, if the voltage measurement is ok, the % should be too - Percentage curves are rather fine.
But different boxes may probe voltages differently; for example, the VTC-Mini measurement is systematically off by -0.05V. So I apply a correction to it, but only on this box, not on the Presa. I'd like to know how different boxes are off on this measure, to have the correct offset for each box.

**Comment by dabugen** [comment]
Could I help with that with my Presa 75 TC somehow?

**Comment by NikitaAtamanchuk** [comment]
@ClockSelect eVic VTC Mini
I must say that when I unplug the charging, voltage returns to 4.21-4.22v

**Comment by GittyHub22** [comment]
The orig firmware has no percentage or voltage, only patches with mfirmwareeditor and i noticed something in nfirmwareeditor device configuration: the battery is set as HE2 (85) even though the device shows GEN in the expert settings and even if you change it in device configuration, the next time it will still show HE2 (or GEN in the expert settings)

**Comment by ClockSelect** [comment]
@dabugen: It would be great if you could compare the battery voltage shown by the box with the real voltage given by an external voltmeter, if you have one.

@NikitaAtamanchuk: voltage rises when charging, and immediately drops when you stop charging, that's perfectly normal. 4.22v is a very high voltage; not too much to be a concern, but a charger should not go so high.

**Comment by NikitaAtamanchuk** [comment]
My evic always charge up to 4.2v.
As far as I know, the li-ion battery needs to be charged to the level of 4.2v.

I specifically made a test. eVic connected to the charge - in version 160 927 - 4.20v, version 161 008 - 4.25v

**Comment by ClockSelect** [comment]
I see. On my VTC mini, the voltage reading of the battery is systematically off by -0.05v; so I added a corrective offset of +0.05v so my box now reads the correct voltage (checked with an external voltmeter).
But it seems that not all boxes are made equal on this regard.
Maybe I should make this configurable.
Anyway, don't be afraid for your battery; it's just the way the number is displayed. The actual voltage sent to the battery does not change from before.

**Comment by NikitaAtamanchuk** [comment]
I'm understood, thank you.
By the way, is it possible to change the charging current? At a current of 500 mA charging is very long. Li-ion batteries can be charged at currents up to 0.5C (for HE4 is 1250 mA)

**Comment by ClockSelect** [comment]
Nope; 500mA is the limit enforced by the USB protocol/specification

**Comment by NikitaAtamanchuk** [comment]
wiki: USB 3.0 increases the current limit from the levels defined by the USB 2.0 specification. Current draw for low-power SuperSpeed devices (ones that are limited to 1 unit load of power) is now 150mA, an increase from 100mA defined in USB 2.0. For high-power SuperSpeed devices, 6 unit loads may be consumed, for a limit of 900mA, 4.5W (4.5 watts), an increase from the limit of 500mA defined in USB 2.0.

**Comment by ClockSelect** [comment]
Agree, but the USB circuitry of the MCU is a USB 1.1.

**Comment by ClockSelect** [comment]
I reset the battery voltage offset correction to zero, and added an option to fix it by hand.
(BVO in the Expert menu).
It should fit everyone :)

**Comment by NikitaAtamanchuk** [comment]
Great, thanks!

**Comment by GittyHub22** [comment]
Still the same issue, but now I know that the voltage showing when off is correct (I measured the battery), The settings in the expert menu (GEN or 30Q) only change the percentage for some reason. And if I change BVO the voltage showing when off and charging is wrong. The difference between off/on is 0.07v (BVO will only let you change max 0.05v but then the wrong voltage is showing when off).

The difference between 30Q en GEN when on = 14% 

Both 3.90v (real should show 3.97v)

30Q: 66%
GEN: 80%

when off it shows around +5% on both.

**Comment by ClockSelect** [comment]
What do you mean by "when off"? Off and charging, I suppose.
Yes, the expert menu setting only changes % calculation.
When you're charging, you're supposed to have a voltage rise by about +0.05, it's perfectly normal and due to the charging process. +0.07, why not.
You're supposed to have
normal < charging on < charging off

**Comment by GittyHub22** [comment]
When the device is turned off.  Not an expert in batteries, but how come dabugen does not have this issue then?

edit: so the 30q percentage is more plausible? I wont focus on this too much from now then :)
