### ISSUE TITLE
"Battery low" on VTwo mini

### ISSUE THREAD

**Issue by aogdb** [ClockSelect/myevic#69]
Hi,

First of all congratulations for this wonderful work!

I post an issue because since the merge of fastadc (commit c65c) my evic VTwo mini frequently shows me the message "Battery low" when I press "Fire" when my battery is approximately 50%. This problem does not concern my evic VTC mini.

thank you in advance

**Comment by ClockSelect** [comment]
Yes, this thing does not seem to work well on all models.
Should be better now.

**Comment by aogdb** [comment]
works well now ! Thanks !
