### ISSUE TITLE
Problem with NFE

### ISSUE THREAD

**Issue by eVic75** [ClockSelect/myevic#70]
Soft from yesteraday: 
NFE v5.1 > myEvic NFE Edition > Device configuration.  I can download settings from box, but I can't upload. I get "Operation completed", but there is no changes in box settings.
Soft from today (latest): 
NFE v5.1 > myEvic NFE Edition > Device configuration. I got window with "Unable to download device settings. Reconnect your device".

Box: eVic VTC Mini.

**Comment by TBXin** [comment]
At this moment settings structure is to different between myEvic and myEvic NFE Edition firmwares.
Thats why Device Configuration is not working properly with original myEvic firmware.

We are working on 'standard' which will provide a capabilities to use Configurator with both firmwares even with different dataflash structures.

**Comment by eVic75** [comment]
Thank you.
