### ISSUE TITLE
Changing coil resistance won´t reflect instantly

### ISSUE THREAD

**Issue by dabugen** [ClockSelect/myevic#73]
Hi,

if changing the coil resistance via the menu (Fire + Plus) -> Coils -> Manage -> TCR (since I use that mode), it is not reflected in the main-screen right away, only after ~10 minutes or ~20 puffs it then changes to the new value I´ve set in the menu. It´s also easy to feel that it wasn´t changed, so it is not just the displaying.

Thank you:)

**Comment by ClockSelect** [comment]
Yes, the menu changes the values in the dataflash but not the values bufferized by the firmware.
I'll have a look.

**Comment by dabugen** [comment]
Ah OK, so it´s a bug?

**Comment by Daveee10** [comment]
Yes. But you can't wait X minutes or X puffs... Take off the atomizer then take it on again..

**Comment by dabugen** [comment]
Hmm, but can´t this be done without having to remove it? Would be much cooler :)

**Comment by ClockSelect** [comment]
I said I'll have a look.

**Comment by dabugen** [comment]
Sorry.. Ok, thanks.

**Comment by ClockSelect** [comment]
Give it a try!

**Comment by eVic75** [comment]
Fixed :) Works properly.

**Comment by dabugen** [comment]
Great, it´s working fine now and changes instantly! Thanks!

**Comment by ClockSelect** [comment]
Great :)
Closing.
