### ISSUE TITLE
RTC Speed

### ISSUE THREAD

**Issue by Daveee10** [ClockSelect/myevic#74]
Hy. I tested your new RTC modification...
From yesterday night (22:00) to today morning (5:00) It works very well, only 1-2 sec of difference (Little faster than the clock on my laptop. BUT. Today the clocks shows 19:00 when the real clock is 18:47... I don't know how why. Maybe because today I'm using the clock on mainview or because when firing the oscillator not give constant value or because the clock correction value maybe not useless...
Have you got any idea?

**Comment by ClockSelect** [comment]
No; I saw this when waking up on my VTwo Mini (I have a VTwo without functioning X32, so I set X32 OFF and the clock is emulated) but not on my Cuboid (also without X32), so it may depend on the hardware. And I wasn't using the boxes since I was sleeping. It has to be investigated. What surprises me is that it _advances_.
Clock speed ratio is not used at all ATM when Light Sleep mode is on.
What's your box model?

**Comment by Daveee10** [comment]
VTC Mini:
HW version: 1.0.0

Wismec Presa 75W

I'm using this two mod whole day and the problem is same..
I think the firing cause the problem.. Maybe we need compare two timer when the mod not sleeping and firing... IMO In the "sleep" mode the oscillator works well now.

**Comment by ClockSelect** [comment]
Well, I found out something: had my two boxes perfectly synched and on time at wake-up today, and my VTC jumped instantly 34 minutes forward at the first puff. Cuboid did not. Then both boxes remained stable.

So the jump into the future seems to happen at the first puff after wake-up. It's a hint.

**Comment by PaoloW8** [comment]
VTC Mini
HW Version: 1.00

clock works fine, after 2 or 3 days still correct (with LSL on) 
but every time I flash a new firmware version the clock goes forward about 20-30 min
(clock on the pc I using for flash is correct)

**Comment by ClockSelect** [comment]
@PaoloW8 : That's interesting. A reproducible thing.
Well, almost. It does it once, and successive flashes do not.
There's something I missed (didn't look at last time): is the date still exact? I mean: does it goes forward 30 min, or 1 day and 30 min? Or even does it go _backward_ 23h and 30 min?

**Comment by PaoloW8** [comment]
I just retried now (with the same firmware file I used this morning) and the clock went ahead by only three minutes. after that I flashed again and the clock is not changed.
I never saw change the date and never saw the clock go backwards, only forward

**Comment by ClockSelect** [comment]
When uploading firmware, clock jump is due to the reset command.
This _should_ be fixed.
But I'm not sure it'll fix every possible clocks jumps.

**Comment by Daveee10** [comment]
Since yesterday the clock works very well. I can't reproduce the clock jumps issue after night. Today morning it's good... The whole day works good too... After firmware uploading the clock jumps only 8 sec (forward)... IMHO this is a good result on a box without X32 crystal...

P.S.: I forgot to say the clock only jumps to forward but never backward...

**Comment by ClockSelect** [comment]
Good news. Let's wait a day or two.

**Comment by Daveee10** [comment]
If I change a battery the clock jumps forward 30 mins

**Comment by bombek5** [comment]
I have the same , jumps forward 30 mins

**Comment by ClockSelect** [comment]
Should no more.

**Comment by PaoloW8** [comment]
Now it seems ok :)
no clock jump on flash firmware
no clock jump on battery swap

thanks @ClockSelect

**Comment by ClockSelect** [comment]
Hope we're done with that.
