### ISSUE TITLE
Awakening delay after sleeping mode

### ISSUE THREAD

**Issue by t2dYuri** [ClockSelect/myevic#75]
Hi again. I noticed a strange awakening-delay with the latest firmware after the device has been inactive for some time (about 3 minutes & more). When i press any button - there is a delay of 1-2 seconds before the display lights up. It's not a problem, but there is the same delay before firing, so i should press the button and wait 1-2 sec. before the first puff...
There was no such problem in my previous installed myEvic version (from Oct 1, 2016).
// _eVic VTwo Mini_ //
Thank You.

**Comment by ClockSelect** [comment]
Strange; I do not experiment this. My delays goes from instant to barely half a second. I'd need more informations to investigate.

**Comment by Daveee10** [comment]
This delay since merge the fasradc branch

**Comment by ClockSelect** [comment]
And even since? I reverted almost everything concerning wake-up moment from this branch. Only remaining difference is an EADC_Open(). I removed it for test purpose (it's useless anyway) and see no difference.
My VTC-Mini wakes up instantly, we VTwo I used the last few days waked up instantly too, the Cuboid I'm currently using wakes up in fraction of a second...
Can't see, really.

**Comment by dabugen** [comment]
I don´t dare to say, but I have the same issue. Sometimes, after being in sleep mode, my Presa 75 TC won´t even turn EVER again until I remove the battery for ~5 seconds, then I can power it back on with pressing fire 5 times as usually. I also didn´t have this with older MyEvic firmwares.

**Comment by acevalsl** [comment]
hi, i have same problem with vtwo mini. Delay is very long. 1 second or more after 1 or two minutes waiting.

**Comment by ClockSelect** [comment]
Do you have the same issues with the LSL option OFF in the Expert menu?

**Comment by acevalsl** [comment]
Yes

**Comment by t2dYuri** [comment]
In VTwo Mini LSL was OFF by default

**Comment by acevalsl** [comment]
I have it off

**Comment by ClockSelect** [comment]
It's gonna be hard since I can't reproduce.
@Daveee10: Are you sure it's since this commit? I can't see in the diff why it would cause this issue.

**Comment by acevalsl** [comment]
i am not secure...... i think since no the last, one more..
in this moment i have old version and work fine, but if i use one more new like 161006 or this not work
sorry my english

**Comment by ClockSelect** [comment]
@acevalsl : and what version are you currently using? so we have the lower bound to search.

**Comment by acevalsl** [comment]
Now I can not see version number, but is one before 161006

**Comment by ClockSelect** [comment]
When you set the USB option in the Expert menu to "DSK" to use the box as an USB disk, what is the date/time of the FIRMWARE.BIN file in the drive?

**Comment by acevalsl** [comment]
Excuseme, but I am in hollidays and I don't have access to PC. Sunday return.
Sorry

**Comment by acevalsl** [comment]
In my PC, bin file say 26 sept.  I see with teamviewer. I used this file for vtwo and this work
![img_1292](https://cloud.githubusercontent.com/assets/22813078/19397831/cfaa6b1a-9249-11e6-975c-40911908d11f.PNG)

**Comment by Daveee10** [comment]
@ClockSelect: The issue come with fastadc but I saw how you removed everything, so I haven't got any idea...

**Comment by ClockSelect** [comment]
If you revert to the manufacturer's firmware, does the problem disappear? (ovbiously, it should)

I got a new VTC DUal two days ago, and it also wakes up and fires near instantly. Not really instant, but far from your 1~2s delay. Say half a second max, seems a reasonable delay to me. No problem with four different models of box, so I can hardly investigate. I can't see anything in the code that would make the box delay more that fractions of a second.

**Comment by acevalsl** [comment]
Which is your vtwo mini hardware version?

**Comment by t2dYuri** [comment]
Rolled into the original fw. v4.04 - instant response from any box state.
![2016-10-15_110807](https://cloud.githubusercontent.com/assets/9843229/19408667/9386151c-92cb-11e6-990d-0f9b3cbcc125.png)
After that I tried to install the latest (today's) myEvic -- got "Update completed" and dead box (no reaction to any actions)
![2016-10-15_111246](https://cloud.githubusercontent.com/assets/9843229/19408669/9dcd84b0-92cb-11e6-9315-4e87a17d1886.png)
Pulled battery off and tried to install myEvic again - got the same result... so I have to work with native firmware for now, but I loved the "ml" counter which allowed me to use non-transparent tanks :(

**Comment by ClockSelect** [comment]
Yes we had some firmware update issues this week-end...
But a dead box is strange. Shouldn't occur.
I know sometimes I must retry falshing several times, but it's rather rare.

**Comment by falconettt** [comment]
Sorry to say,
Just uploaded new firmware, and have awakening-delay after the device has been inactive for some time.
It's not always but sometimes. 3-5 fire clicks make box alive again. LSL change doesn't help.
/evic-mini, hv 1.01/

**Comment by acevalsl** [comment]
Hi, I'm testing last software and delay is missing.
Please test it for answer..........

**Comment by t2dYuri** [comment]
Really. With the latest  myEvic updates I have an instant response too.
Thank You.
// _eVic VTwo Mini, HW 1.00, TC Ti_ //

**Comment by ClockSelect** [comment]
That's great, but... _Why_ ???
I'd really like to figure out the point.

**Comment by acevalsl** [comment]
resistance measure??

**Comment by falconettt** [comment]
I did some research and found the moment of occurrence. 
It is not a delay, box just shuts down under the following circumstances:

"Long fire protection" - LFP.

So you inhale till LFP triggered, see this annoying "LFP screen" but do not touch anything just put your box aside. Screensaver works and mod goes to sleep.  At this moment you have mod switched off (why???).
You can power it back on only with pressing fire 5 times. 

If LFP is not triggered you will not get this "delay".

By the way, do not waste time on nonsense, the whole world is breathlessly awaiting compatibility with RX2/3.^^

**Comment by ClockSelect** [comment]
Yes, box switches off 10 seconds after after a long fire without response - it's on purpose, it considers it's in your pocket.

But switching off, requesting five clicks to wake up, and having a wake-up delay are two different things.

**Comment by acevalsl** [comment]
I never need press 5 times for wake up

**Comment by ClockSelect** [comment]
You don't have a Presa ^^

**Comment by ClockSelect** [comment]
I think I found the _why_.

**Comment by acevalsl** [comment]
??????

**Comment by ClockSelect** [comment]
Seems closable.
