### ISSUE TITLE
Cuboid real time resistance and voltage of both batteries in third line

### ISSUE THREAD

**Issue by rocknrollman** [ClockSelect/myevic#76]
Hey) Delivered your firmware on a cuboid. It very cool. Everything what i dream that: display of resistance in real time in thirds line, like in evic and that in it the voltage of both batteries was displayed. It is possible to make it? I will be very grateful)

**Comment by ClockSelect** [comment]
The resistance in real-time with a milliohm accuracy on third line is already available.
And if you look closely, you'll see that the coil on second line is _also_ in real-time.

For the both batteries: it's in the TODO list, but I don't really consider it as urgent - What you see is the voltage and level of the _lowest_ of the two batteries. As long as you do not have an imbalanced warning, you know that the second battery is at most at +0.02V from the first. Is it really worth displaying two identical numbers?

**Comment by rocknrollman** [comment]
In an eviс just resistance is updated with a bigger frequency than in a cuboid, here I also want effect as in an eviс. And concerning batteries, here already on your discretion, for me it is just a habit :)

**Comment by ClockSelect** [comment]
They're updated every tenth of a second when firing, and every few seconds when idle, on both boxes.

**Comment by ClockSelect** [comment]
I improved the refresh rate of the real-time rez, maybe it will help^^
I agree it's better.

**Comment by ClockSelect** [comment]
I'll keep this issue open since I think many others will ask for dual-battery display.

**Comment by rocknrollman** [comment]
Thank you, resistance now is perfect!

**Comment by bluenazgul** [comment]
another feature for 2 Battery Mods would be to Diplay the two battery at the bottom line like in original Fimware

But for the Theme Creators it would be easier to keep the single icon

**Comment by nbraunstein** [comment]
Is two battery display possible on the rx 2/3?

**Comment by ClockSelect** [comment]
No, battery display is unified.
All batteries are supposed to be between 0.3V between the lowest and max voltage; if not, a visible balance warning is issued.
You can always consult comprehensive battery voltages in the Expert>BVO menu, or by switching the box off and holding Fire-<->.
