### ISSUE TITLE
New firmware not working Wismec Presa

### ISSUE THREAD

**Issue by lojpek** [ClockSelect/myevic#78]
Hello.
I download today build and upload to my presa. After upload there is black screen, nothing work. Only when I remove battery, put it back and plug into usb I can upload other firmware.
regards

**Comment by Daveee10** [comment]
I'm using the latest firmware everytime when @ClockSelect update the repo and I haven't got any issue with my Presa and my VTC Mini. I think the update procedure make a mistake and your mod goes to 'Bootloader'. After flashing another firmware it booted correctly.  Now you can use the latest again

**Comment by lojpek** [comment]
I have uploaded to presa original software and then from clockSelect and it's works. Thanks ;) closed
