### ISSUE TITLE
Interface select

### ISSUE THREAD

**Issue by Filo301** [ClockSelect/myevic#79]
Can you make interface chose?
I mean evic v5.04, evic v3.04, wismec, etc interface layout.
It should be useful.
Thank You for good work!

**Comment by ClockSelect** [comment]
The whole interface/event code would have to be revamped for modularity to do this well. There is not enough memory space to just "add" some new interfaces. Before 3.0, the firmware had an interface change feature that was eventually removed, I guess for complexity reasons.
It's a tremendous work and not planned in a near future.

**Comment by Filo301** [comment]
Ok, thanks!
