### ISSUE TITLE
USB disconnect on sleep mode

### ISSUE THREAD

**Issue by fonix232** [ClockSelect/myevic#85]
The title makes it quite obvious. It is not an issue per say, but it would be nice if there was an active VCOM/HID connection, then the board would not go into deep sleep - keep the connection alive. In theory it shouldn't use much power, given how the device is already externally powered.

**Comment by ClockSelect** [comment]
Why would you want that?

**Comment by fonix232** [comment]
For tinkering, mainly, testing out stuff. I was trying to communicate with my Cuboid, and it kept disconnecting if I didn't set the sleep timeout higher or kept pressing the button, which was quite annoying.

**Comment by ClockSelect** [comment]
Try to set Screen>Protection>Saver to "Off", and Stealth mode to Off also (Fire+Left).
The box should no longer enter deep sleep mode while USB is attached.

**Comment by ClockSelect** [comment]
No news good news

**Comment by fonix232** [comment]
Sorry for not replying, haven't got the notification. It is indeed a solution, however sleep mode would be preferred to turn on only if there's no charging.

Seeing how you already made a commit to fix this, I'll see if it fixes my other problem I noticed lately - namely, the batteries are not charged after a time (presumably after entering sleep mode?). It simply shows charging, and voltage stays the same.

**Comment by fonix232** [comment]
Okay, it indeed fixed the charging issue I was experiencing. Instead of charging 1-2% in 4 hours, I charged from 35% to 99% in two (using two LG HG2)

**Comment by ClockSelect** [comment]
Great!
