### ISSUE TITLE
Where to donate?

### ISSUE THREAD

**Issue by dabugen** [ClockSelect/myevic#88]
Now honestly, you guys did put so much work into this already and are still adding new features + new releases daily which I am download almost each day as well, yet I can´t see where I could donate for that great stuff... Please let me know:)

**Comment by ClockSelect** [comment]
I didn't expect that, so didn't do anything this way.

**Comment by fonix232** [comment]
I double this. I know jacksh*t about C/C++ and working with hardware level stuff, but I use these awesome tweaks you did (not to mention the months' work with reversing the stock firmware!), so the least I can do is give you some beer money. I know you're not doing this for the cash, but in a way, many would like to show appreciation 😄
