### ISSUE TITLE
Smart mode

### ISSUE THREAD

**Issue by Nestorfish** [ClockSelect/myevic#90]
Hello,

Sorry for another pollution into "Issues", but... what is smart mode?
I see no discrimination in your code between variable wattage and smart modes, as I did using official firmware.
Did you manage to understand any difference from original firmware?

**Comment by ClockSelect** [comment]
Smart mode is a variable wattage mode; there's no difference really betwen power and smart beyond the interface, and the fact that smart mode is meant to work with some specific manufacturer's coils so that it shows some predifined wattage range and some sweet spot with those specific resistances.
