### ISSUE TITLE
Exiting game? [Latest Update]

### ISSUE THREAD

**Issue by SEEKNDESTROY** [ClockSelect/myevic#94]
**Box Model: RX200S**

**Coil setup: Does not apply to my issue**

Just installed the latest update and was wondering how do you exit out of the game? I have to remove a battery to exit the game... I've tried all sorts of button combinations and nothing will exit the game. Any advice?

Thanks

**Comment by Daveee10** [comment]
Press plus regulatory button (+) and fire button for 3 seconds

**Comment by SEEKNDESTROY** [comment]
Thanks, that worked!
