### ISSUE TITLE
RX200S logo

### ISSUE THREAD

**Issue by XqqsMe** [ClockSelect/myevic#99]
Hi,
Just updated custom firmware. Excellent job! I was trying to set up to show custom logo but it's not having it on screen even though it's selected. Other screen savers such as snow are working fine. Any help is appreciated. Also will the clock and date and other things lose their setting when changing batteries? Thanks

**Comment by bluenazgul** [comment]
Logo's have to be 64*40 atm (may change soon) - since we dont have an RTC, Clock Settings may loose on chanaging batteries

**Comment by XqqsMe** [comment]
So the bmp files will not work, correct?

**Comment by bluenazgul** [comment]
the Logos have to be bmp (64*40 Pixel monochrom Bitmap)

**Comment by XqqsMe** [comment]
Mine are and work fine with the Wismec latest update. I've uploaded to device but new evic software not showing it.

**Comment by bluenazgul** [comment]
That is because the Wismec RX200S uses default 64x48 Pixel Logos and the current myevic release uses smaller Logos (only 64x40 Pixel)

This will change in future when @ClockSelect has the it done

**Comment by ClockSelect** [comment]
Logo stuff has been developped and will be released soon.
For the clock thing: real-time information is lost when changing batteries if you're not fast enough (around 10s). But you can change batteries while plugged on the USB and time will be kept.

**Comment by XqqsMe** [comment]
Ah. Gotcha now. Sorry for the confusion.

**Comment by XqqsMe** [comment]
Good info on the battery issue. Keep up the good work!

**Comment by ClockSelect** [comment]
48 lines Logos should work, now.

**Comment by XqqsMe** [comment]
Thanks. I'll have to get new bin file correct?

**Comment by ClockSelect** [comment]
correct.

**Comment by afol2** [comment]
64x48 should work for cuboid/evic too ? i dont know id the dimension of the screen are the same in RX200s / RX2/3 and the cuboid/evic @ClockSelect

**Comment by XqqsMe** [comment]
Updated my bin file. 64x48 bmp logo on RX200S working great! Thanks!

**Comment by bluenazgul** [comment]
Now only the NFirmwareEditor needs to get Compatible with the supported Logo sizes.

**Comment by ClockSelect** [comment]
@afol2 : they should work on all 14 supported boxes^^

**Comment by afol2** [comment]
Cool..! @ClockSelect

**Comment by XqqsMe** [comment]
Just noticed that wattage on the RX200S only goes to 91 and not 250.
